// 朝鮮／韓國歷史時間線資料
// 年份均為近似學術估計，負數為西元前
// 三國時代（高句麗／百濟／新羅）為並行政權，君主列表依年代交錯排列

const KR_ROW_LABELS = ['主要時期', '歷代君主'];

const KR_GROUPS = [

  // ══ Row 0 主要時期══════════════════════════════════════════════════
  { name:'古朝鮮',          en:'Gojoseon – legendary founding by Dangun, earliest Korean state', start: -2333, end: -108, color:'#78350f', row:0, dim:true, wikiEn:'Gojoseon' },
  { name:'三國時代',        en:'Three Kingdoms – Goguryeo, Baekje, Silla compete for the peninsula', start: -57, end: 668, color:'#991b1b', row:0, wikiEn:'Three_Kingdoms_of_Korea' },
  { name:'統一新羅',        en:'Unified Silla – unifies most of the peninsula with Tang alliance', start:  668, end:  935, color:'#b91c1c', row:0, wikiEn:'Unified_Silla' },
  { name:'渤海國',          en:'Balhae – parallel northern successor state to Goguryeo',        start:  698, end:  926, color:'#7c2d12', row:0, dim:true, wikiEn:'Balhae' },
  { name:'後三國時代',      en:'Later Three Kingdoms – Silla fragments amid civil war',          start:  892, end:  936, color:'#dc2626', row:0, dim:true, wikiEn:'Later_Three_Kingdoms_of_Korea' },
  { name:'高麗王朝',        en:'Goryeo – founded by Wang Geon; origin of the name "Korea"',      start:  918, end: 1392, color:'#0369a1', row:0, wikiEn:'Goryeo' },
  { name:'朝鮮王朝',        en:'Joseon – Confucian dynasty founded by Yi Seong-gye',             start: 1392, end: 1897, color:'#166534', row:0, wikiEn:'Joseon' },
  { name:'大韓帝國',        en:'Korean Empire – Gojong declares empire seeking sovereignty',     start: 1897, end: 1910, color:'#15803d', row:0, dim:true, wikiEn:'Korean_Empire' },
  { name:'日本殖民統治',    en:'Japanese Colonial Period',                                       start: 1910, end: 1945, color:'#4b5563', row:0, dim:true, wikiEn:'Korea_under_Japanese_rule' },
  { name:'南北韓分治',      en:'Division of Korea – DPRK and ROK established',                   start: 1945, end: 2026, color:'#eab308', row:0, wikiEn:'Division_of_Korea' },

  // ══ Row 1 歷代君主════════════════════════════════════════════════
  // ── 高句麗（循環色：#991b1b,#b91c1c,#dc2626）─────────────────────
  { name:'東明聖王', en:'King Dongmyeong (Jumong) – legendary founder of Goguryeo',
    start:  -37, end:  -19, color:'#991b1b', row:1, dim:true, wikiEn:'Jumong' },
  { name:'美川王', en:'King Micheon of Goguryeo – expanded territory, defeated Lelang',
    start:  300, end:  331, color:'#b91c1c', row:1, dim:true },
  { name:'廣開土大王', en:'King Gwanggaeto the Great of Goguryeo – greatest territorial expansion in Korean history',
    start:  391, end:  413, color:'#dc2626', row:1, wikiEn:'Gwanggaeto_the_Great' },
  { name:'長壽王', en:'King Jangsu of Goguryeo – moved capital to Pyongyang, longest reign',
    start:  413, end:  491, color:'#991b1b', row:1, wikiEn:'Jangsu_of_Goguryeo' },

  // ── 百濟（循環色：#0369a1,#0284c7,#0ea5e9）───────────────────────
  { name:'近肖古王', en:'King Geunchogo of Baekje – kingdom\'s peak power and territory',
    start:  346, end:  375, color:'#0369a1', row:1, dim:true },
  { name:'武寧王', en:'King Muryeong of Baekje – stabilized kingdom, strong China/Japan ties',
    start:  501, end:  523, color:'#0284c7', row:1, wikiEn:'Muryeong_of_Baekje' },
  { name:'聖王', en:'King Seong of Baekje – sent Buddhism to Japan; killed in war with Silla',
    start:  523, end:  554, color:'#0ea5e9', row:1, dim:true },

  // ── 新羅（循環色：#166534,#15803d,#16a34a）───────────────────────
  { name:'法興王', en:'King Beopheung of Silla – adopted Buddhism as the state religion',
    start:  514, end:  540, color:'#166534', row:1, dim:true },
  { name:'善德女王', en:'Queen Seondeok of Silla – first reigning queen of Silla',
    start:  632, end:  647, color:'#15803d', row:1, wikiEn:'Queen_Seondeok_of_Silla' },
  { name:'武烈王', en:'King Muyeol (Kim Chunchu) of Silla – allied with Tang, began the unification wars',
    start:  654, end:  661, color:'#16a34a', row:1, dim:true },
  { name:'文武王', en:'King Munmu of Silla – completed the unification of the Three Kingdoms (668)',
    start:  661, end:  681, color:'#166534', row:1, wikiEn:'Munmu_of_Silla' },

  // ── 高麗王朝（循環色：#0369a1,#0284c7,#0ea5e9,#38bdf8）───────────
  { name:'太祖 王建', en:'Taejo (Wang Geon) – founder of the Goryeo dynasty',
    start:  918, end:  943, color:'#0369a1', row:1, wikiEn:'Taejo_of_Goryeo' },
  { name:'光宗', en:'Gwangjong – strengthened royal authority, introduced civil service exams',
    start:  949, end:  975, color:'#0284c7', row:1, dim:true },
  { name:'成宗', en:'Seongjong – Confucian administrative reforms',
    start:  981, end:  997, color:'#0ea5e9', row:1, dim:true },
  { name:'顯宗', en:'Hyeonjong – repelled the Khitan invasions',
    start: 1009, end: 1031, color:'#38bdf8', row:1, dim:true },
  { name:'文宗', en:'Munjong – golden age of Goryeo culture and stability',
    start: 1046, end: 1083, color:'#0369a1', row:1 },
  { name:'仁宗', en:'Injong – faced the Yi Ja-gyeom rebellion',
    start: 1122, end: 1146, color:'#0284c7', row:1, dim:true },
  { name:'毅宗', en:'Uijong – overthrown in the military coup (Musin Revolt)',
    start: 1146, end: 1170, color:'#0ea5e9', row:1, dim:true },
  { name:'高宗', en:'Gojong of Goryeo – endured the Mongol invasions, moved capital to Ganghwa Island',
    start: 1213, end: 1259, color:'#38bdf8', row:1, wikiEn:'Gojong_of_Goryeo' },
  { name:'元宗', en:'Wonjong – submitted to Mongol Yuan dominance',
    start: 1259, end: 1274, color:'#0369a1', row:1, dim:true },
  { name:'恭愍王', en:'Gongmin – attempted anti-Mongol reforms and independence',
    start: 1351, end: 1374, color:'#0284c7', row:1, wikiEn:'Gongmin_of_Goryeo' },

  // ── 朝鮮王朝（27代，循環色：#166534,#15803d,#16a34a,#22c55e）─────
  { name:'太祖', en:'Taejo (Yi Seong-gye) – founder of the Joseon dynasty',
    start: 1392, end: 1398, color:'#166534', row:1, wikiEn:'Taejo_of_Joseon' },
  { name:'定宗', en:'Jeongjong – brief, overshadowed reign',
    start: 1398, end: 1400, color:'#15803d', row:1, dim:true },
  { name:'太宗', en:'Taejong – consolidated royal power ruthlessly',
    start: 1400, end: 1418, color:'#16a34a', row:1, wikiEn:'Taejong_of_Joseon' },
  { name:'世宗大王', en:'Sejong the Great – created Hangul, golden age of science and culture',
    start: 1418, end: 1450, color:'#22c55e', row:1, wikiEn:'Sejong_the_Great' },
  { name:'文宗', en:'Munjong – frail, short reign',
    start: 1450, end: 1452, color:'#166534', row:1, dim:true },
  { name:'端宗', en:'Danjong – child king, deposed and killed by his uncle',
    start: 1452, end: 1455, color:'#15803d', row:1, dim:true },
  { name:'世祖', en:'Sejo – usurped the throne from nephew Danjong',
    start: 1455, end: 1468, color:'#16a34a', row:1, dim:true },
  { name:'成宗', en:'Seongjong – completed the Gyeongguk daejeon legal code',
    start: 1469, end: 1494, color:'#22c55e', row:1 },
  { name:'燕山君', en:'Yeonsangun – tyrant king, deposed in a coup',
    start: 1494, end: 1506, color:'#166534', row:1, dim:true, wikiEn:'Yeonsangun' },
  { name:'中宗', en:'Jungjong – installed after the coup against Yeonsangun',
    start: 1506, end: 1544, color:'#15803d', row:1, dim:true },
  { name:'明宗', en:'Myeongjong – dominated by regents and factionalism',
    start: 1545, end: 1567, color:'#16a34a', row:1, dim:true },
  { name:'宣祖', en:'Seonjo – reigned during the Imjin War (Japanese invasions, 1592–98)',
    start: 1567, end: 1608, color:'#22c55e', row:1, wikiEn:'Seonjo_of_Joseon' },
  { name:'光海君', en:'Gwanghaegun – pragmatic diplomat, deposed in a coup',
    start: 1608, end: 1623, color:'#166534', row:1, dim:true },
  { name:'仁祖', en:'Injo – faced the Manchu (Qing) invasions, humiliating surrender',
    start: 1623, end: 1649, color:'#15803d', row:1, wikiEn:'Injo_of_Joseon' },
  { name:'孝宗', en:'Hyojong – planned a failed "Northern Expedition" against Qing',
    start: 1649, end: 1659, color:'#16a34a', row:1, dim:true },
  { name:'顯宗', en:'Hyeonjong – era of ritual and mourning disputes among factions',
    start: 1659, end: 1674, color:'#22c55e', row:1, dim:true },
  { name:'肅宗', en:'Sukjong – long reign, intense factional strife',
    start: 1674, end: 1720, color:'#166534', row:1 },
  { name:'景宗', en:'Gyeongjong – sickly, short reign amid factional turmoil',
    start: 1720, end: 1724, color:'#15803d', row:1, dim:true },
  { name:'英祖', en:'Yeongjo – longest-reigning king; reforms; executed his own son',
    start: 1724, end: 1776, color:'#16a34a', row:1, wikiEn:'Yeongjo' },
  { name:'正祖', en:'Jeongjo – enlightened reformer, built the Hwaseong Fortress',
    start: 1776, end: 1800, color:'#22c55e', row:1, wikiEn:'Jeongjo_of_Joseon' },
  { name:'純祖', en:'Sunjo – power seized by in-law (sedo) clans',
    start: 1800, end: 1834, color:'#166534', row:1, dim:true },
  { name:'憲宗', en:'Heonjong – child king, continued clan domination',
    start: 1834, end: 1849, color:'#15803d', row:1, dim:true },
  { name:'哲宗', en:'Cheoljong – weak king, peak of sedo politics',
    start: 1849, end: 1863, color:'#16a34a', row:1, dim:true },
  { name:'高宗', en:'Gojong – declared the Korean Empire (1897); forced to abdicate',
    start: 1863, end: 1907, color:'#22c55e', row:1, wikiEn:'Gojong_of_Korea' },
  { name:'純宗', en:'Sunjong – last king/emperor, throne ended by Japanese annexation',
    start: 1907, end: 1910, color:'#166534', row:1, dim:true, wikiEn:'Sunjong_of_Korea' },
];

const KR_EVENTS = [
  // ── 古朝鮮與三國時代 ───────────────────────────────────────────────
  { year: -2333, text: '傳說中檀君建立古朝鮮，朝鮮半島最早的國家' },
  { year:  -108, text: '古朝鮮被漢朝所滅' },
  { year:   -57, text: '新羅建國（傳統紀年）' },
  { year:   -37, text: '高句麗建國（傳統紀年）' },
  { year:   -18, text: '百濟建國（傳統紀年）' },
  { year:   372, text: '佛教傳入高句麗' },
  { year:   384, text: '佛教傳入百濟' },
  { year:   391, text: '廣開土大王即位，展開高句麗史上最大規模的擴張' },
  { year:   527, text: '新羅正式採納佛教為國教' },
  { year:   612, text: '薩水之戰：高句麗擊退隋朝大軍入侵' },
  { year:   645, text: '高句麗擊退唐朝入侵' },
  { year:   660, text: '新羅與唐朝聯軍滅百濟' },
  { year:   668, text: '新羅與唐朝聯軍滅高句麗，新羅統一朝鮮半島大部' },

  // ── 統一新羅與渤海 ─────────────────────────────────────────────────
  { year:   698, text: '大祚榮在高句麗故地建立渤海國' },
  { year:   892, text: '新羅陷入內亂，後三國時代開始（後百濟、後高句麗、新羅並立）' },
  { year:   918, text: '王建建立高麗王朝' },
  { year:   926, text: '渤海國被契丹遼朝所滅' },
  { year:   935, text: '新羅正式向高麗投降' },
  { year:   936, text: '高麗完成朝鮮半島統一' },

  // ── 高麗王朝 ───────────────────────────────────────────────────────
  { year:   993, text: '契丹遼朝首次入侵高麗，此後侵擾持續至1019年' },
  { year:  1170, text: '武臣政變（庚寅之亂）推翻文官貴族統治，武人政權開始' },
  { year:  1231, text: '蒙古開始入侵高麗，戰爭持續至1259年' },
  { year:  1270, text: '高麗成為蒙古元朝附庸國' },
  { year:  1388, text: '李成桂發動威化島回軍政變，掌握高麗實權' },

  // ── 朝鮮王朝 ───────────────────────────────────────────────────────
  { year:  1392, text: '李成桂建立朝鮮王朝，即太祖' },
  { year:  1394, text: '遷都漢城（今首爾）' },
  { year:  1443, text: '世宗大王創制訓民正音（諺文，即韓文字母）' },
  { year:  1446, text: '《訓民正音》正式頒布，韓文開始推廣使用' },
  { year:  1592, text: '壬辰倭亂：豐臣秀吉發動第一次侵略朝鮮戰爭' },
  { year:  1598, text: '李舜臣率龜船艦隊多次重創日軍水師，助朝鮮擊退豐臣秀吉侵略' },
  { year:  1627, text: '後金（滿洲）第一次入侵朝鮮（丁卯胡亂）' },
  { year:  1636, text: '清朝第二次入侵朝鮮（丙子胡亂），朝鮮被迫向清朝稱臣' },
  { year:  1785, text: '天主教開始在朝鮮傳播，隨後遭到多次迫害' },

  // ── 開國、大韓帝國與日治時期 ───────────────────────────────────────
  { year:  1863, text: '興宣大院君攝政，推行鎖國政策' },
  { year:  1876, text: '《江華條約》簽署，朝鮮被迫對日本開國' },
  { year:  1882, text: '壬午軍亂：朝鮮軍隊譁變，引發清日兩國介入' },
  { year:  1884, text: '甲申政變：開化黨發動的改革政變失敗' },
  { year:  1894, text: '東學農民革命爆發，成為甲午戰爭導火線之一' },
  { year:  1895, text: '日本策動「乙未事變」，明成皇后（閔妃）遭日本人暗殺' },
  { year:  1897, text: '高宗稱帝，建立大韓帝國，試圖擺脫外國干涉' },
  { year:  1904, text: '日俄戰爭爆發，日本藉此擴大對朝鮮的控制' },
  { year:  1905, text: '《乙巳條約》簽訂，大韓帝國淪為日本保護國' },
  { year:  1907, text: '高宗被迫退位，純宗即位為末代君主' },
  { year:  1910, text: '《日韓合併條約》簽署，朝鮮半島正式淪為日本殖民地' },
  { year:  1919, text: '三一運動爆發，全國性抗日示威；大韓民國臨時政府隨後於上海成立' },
  { year:  1945, text: '8月15日日本投降，朝鮮半島光復，隨後以北緯38度線劃分南北占領區' },

  // ── 南北分治與韓戰 ─────────────────────────────────────────────────
  { year:  1948, text: '大韓民國（南韓）與朝鮮民主主義人民共和國（北韓）先後成立，南北分治正式形成' },
  { year:  1950, text: '韓戰爆發（1950–1953），北韓南侵引發國際介入' },
  { year:  1953, text: '《朝鮮停戰協定》簽署，確立非軍事區（DMZ），南北分裂延續至今' },
];
