// 中國歷代帝王資料（周、秦、漢、唐、宋、明、清）
// row: 5，配合 ZH_ROW_LABELS 第六欄「帝王」
// 周王無年號、無廟號，name 用諡號（如武王、成王）；personal 用姬姓名
// 每個朝代循環使用 3–4 色，以區分相鄰君主

const ZH_EMPERORS = [

  // ══ 西周（-1046 ~ -771）══════════════════════════════════════════
  // 循環色：['#d97706','#f59e0b','#fbbf24','#fde68a']
  // -841 ~ -827 為共和行政（周召二公攝政），無在位君主，故留空
  { name:'武王', en:'King Wu of Zhou – defeated Shang, founded Zhou dynasty',
    start:-1046, end:-1043, color:'#d97706', row:5, personal:'姬發', wikiEn:'King_Wu_of_Zhou' },
  { name:'成王', en:'King Cheng of Zhou – Duke of Zhou served as regent',
    start:-1042, end:-1021, color:'#f59e0b', row:5, personal:'姬誦', wikiEn:'King_Cheng_of_Zhou' },
  { name:'康王', en:'King Kang of Zhou – peaceful golden age of early Zhou',
    start:-1020, end:-996,  color:'#fbbf24', row:5, personal:'姬釗', wikiEn:'King_Kang_of_Zhou' },
  { name:'昭王', en:'King Zhao of Zhou – died on southern campaign',
    start:-995,  end:-977,  color:'#fde68a', row:5, personal:'姬瑕', wikiEn:'King_Zhao_of_Zhou' },
  { name:'穆王', en:'King Mu of Zhou – legendary traveller, met Queen Mother of the West',
    start:-976,  end:-922,  color:'#d97706', row:5, personal:'姬滿', wikiEn:'King_Mu_of_Zhou' },
  { name:'共王', en:'King Gong of Zhou',
    start:-922,  end:-900,  color:'#f59e0b', row:5, personal:'姬繄扈' },
  { name:'懿王', en:'King Yi of Zhou',
    start:-899,  end:-892,  color:'#fbbf24', row:5, personal:'姬囏' },
  { name:'孝王', en:'King Xiao of Zhou',
    start:-891,  end:-886,  color:'#fde68a', row:5, personal:'姬辟方', wikiEn:'King_Xiao_of_Zhou' },
  { name:'夷王', en:'King Yi II of Zhou',
    start:-885,  end:-878,  color:'#d97706', row:5, personal:'姬燮' },
  { name:'厲王', en:'King Li of Zhou – tyrannical rule, exiled by nobles in 841 BC',
    start:-877,  end:-841,  color:'#f59e0b', row:5, personal:'姬胡', wikiEn:'King_Li_of_Zhou' },
  // -841 ~ -827 共和行政（無君）
  { name:'宣王', en:'King Xuan of Zhou – Zhou revival, first year of verified Chinese chronology',
    start:-827,  end:-782,  color:'#fbbf24', row:5, personal:'姬靜', wikiEn:'King_Xuan_of_Zhou' },
  { name:'幽王', en:'King You of Zhou – lit beacon fires for concubine Bao Si; Western Zhou ended',
    start:-781,  end:-771,  color:'#fde68a', row:5, personal:'姬宮湦', wikiEn:'King_You_of_Zhou' },

  // ══ 東周（-770 ~ -256）══════════════════════════════════════════
  // 春秋（-770 ~ -476）+ 戰國（-475 ~ -256）
  // 循環色：['#78350f','#92400e','#b45309','#d97706']
  { name:'平王', en:'King Ping of Zhou – moved capital east to Luoyi, began Eastern Zhou',
    start:-770,  end:-720,  color:'#78350f', row:5, personal:'姬宜臼', wikiEn:'King_Ping_of_Zhou' },
  { name:'桓王', en:'King Huan of Zhou – defeated by Zheng at Battle of Xuge',
    start:-719,  end:-697,  color:'#92400e', row:5, personal:'姬林', wikiEn:'King_Huan_of_Zhou' },
  { name:'莊王', en:'King Zhuang of Zhou',
    start:-696,  end:-682,  color:'#b45309', row:5, personal:'姬佗' },
  { name:'釐王', en:'King Xi of Zhou',
    start:-681,  end:-677,  color:'#d97706', row:5, personal:'姬胡齊' },
  { name:'惠王', en:'King Hui of Zhou',
    start:-676,  end:-652,  color:'#78350f', row:5, personal:'姬閬' },
  { name:'襄王', en:'King Xiang of Zhou – era of Duke Huan of Qi as hegemon',
    start:-651,  end:-619,  color:'#92400e', row:5, personal:'姬鄭' },
  { name:'頃王', en:'King Qing of Zhou',
    start:-618,  end:-613,  color:'#b45309', row:5, personal:'姬壬臣' },
  { name:'匡王', en:'King Kuang of Zhou',
    start:-612,  end:-607,  color:'#d97706', row:5, personal:'姬班' },
  { name:'定王', en:'King Ding of Zhou – Chu asked about Zhou\'s bronze ritual vessels',
    start:-606,  end:-586,  color:'#78350f', row:5, personal:'姬瑜' },
  { name:'簡王', en:'King Jian of Zhou',
    start:-585,  end:-572,  color:'#92400e', row:5, personal:'姬夷' },
  { name:'靈王', en:'King Ling of Zhou',
    start:-571,  end:-545,  color:'#b45309', row:5, personal:'姬泄心' },
  { name:'景王', en:'King Jing of Zhou – cast large bells, succession dispute after death',
    start:-544,  end:-520,  color:'#d97706', row:5, personal:'姬貴' },
  { name:'悼王', en:'King Dao of Zhou – short reign amid civil war',
    start:-520,  end:-519,  color:'#78350f', row:5, personal:'姬猛' },
  { name:'敬王', en:'King Jing II of Zhou – Zhou authority further diminished',
    start:-519,  end:-476,  color:'#92400e', row:5, personal:'姬丐' },
  { name:'元王', en:'King Yuan of Zhou',
    start:-475,  end:-469,  color:'#b45309', row:5, personal:'姬仁' },
  { name:'貞定王', en:'King Zhending of Zhou',
    start:-468,  end:-441,  color:'#d97706', row:5, personal:'姬介' },
  { name:'哀王', en:'King Ai of Zhou – killed by brother after months',
    start:-441,  end:-440,  color:'#78350f', row:5, personal:'姬去疾' },
  { name:'思王', en:'King Si of Zhou – killed by brother after months',
    start:-440,  end:-439,  color:'#92400e', row:5, personal:'姬叔' },
  { name:'考王', en:'King Kao of Zhou',
    start:-439,  end:-426,  color:'#b45309', row:5, personal:'姬嵬' },
  { name:'威烈王', en:'King Weilie of Zhou – recognized Han, Wei, Zhao as lords',
    start:-425,  end:-402,  color:'#d97706', row:5, personal:'姬午' },
  { name:'安王', en:'King An of Zhou',
    start:-401,  end:-376,  color:'#78350f', row:5, personal:'姬驕' },
  { name:'烈王', en:'King Lie of Zhou',
    start:-375,  end:-369,  color:'#92400e', row:5, personal:'姬喜' },
  { name:'顯王', en:'King Xian of Zhou – long reign, Zhou a mere formality',
    start:-368,  end:-321,  color:'#b45309', row:5, personal:'姬扁' },
  { name:'慎靚王', en:'King Shenjing of Zhou',
    start:-320,  end:-315,  color:'#d97706', row:5, personal:'姬定' },
  { name:'赧王', en:'King Nan of Zhou – last Zhou king, died as Qin took Luoyi',
    start:-314,  end:-256,  color:'#78350f', row:5, personal:'姬延', wikiEn:'King_Nan_of_Zhou' },

  // ══ 秦（-221 ~ -206）══════════════════════════════════════════════
  // 秦無年號（年號制度始於漢武帝建元元年 -140）
  { name:'始皇帝', en:'Qin Shi Huang – First Emperor of China',
    start:-221, end:-210, color:'#6b7280', row:5, personal:'嬴政', wikiEn:'Qin_Shi_Huang' },
  { name:'秦二世', en:'Qin Er Shi',
    start:-210, end:-207, color:'#9ca3af', row:5, personal:'胡亥', wikiEn:'Qin_Er_Shi' },
  { name:'子嬰',   en:'Ziying – last ruler of Qin',
    start:-207, end:-206, color:'#d1d5db', row:5, personal:'子嬰' },

  // ══ 西漢（-206 ~ 9）══════════════════════════════════════════════
  // 循環色：['#dc2626','#ef4444','#f87171','#fca5a5']
  { name:'高帝', en:'Emperor Gaozu of Han',
    start:-206, end:-195, color:'#dc2626', row:5, nianHao:'（無）', personal:'劉邦', wikiEn:'Emperor_Gaozu_of_Han' },
  { name:'惠帝', en:'Emperor Hui of Han',
    start:-195, end:-188, color:'#ef4444', row:5, nianHao:'（無）', personal:'劉盈', wikiEn:'Emperor_Hui_of_Han' },
  // -188 ~ -180 呂后攝政，無正式皇帝（略）
  { name:'文帝', en:'Emperor Wen of Han',
    start:-180, end:-157, color:'#f87171', row:5, nianHao:'（無）', personal:'劉恆', wikiEn:'Emperor_Wen_of_Han' },
  { name:'景帝', en:'Emperor Jing of Han',
    start:-157, end:-141, color:'#fca5a5', row:5, nianHao:'（無）', personal:'劉啟', wikiEn:'Emperor_Jing_of_Han' },
  { name:'武帝', en:'Emperor Wu of Han – first to use era names',
    start:-141, end:-87,  color:'#dc2626', row:5, nianHao:'建元', personal:'劉徹', wikiEn:'Emperor_Wu_of_Han' },
  { name:'昭帝', en:'Emperor Zhao of Han',
    start:-87,  end:-74,  color:'#ef4444', row:5, nianHao:'始元', personal:'劉弗陵', wikiEn:'Emperor_Zhao_of_Han' },
  { name:'宣帝', en:'Emperor Xuan of Han',
    start:-74,  end:-49,  color:'#f87171', row:5, nianHao:'本始', personal:'劉詢', wikiEn:'Emperor_Xuan_of_Han' },
  { name:'元帝', en:'Emperor Yuan of Han',
    start:-49,  end:-33,  color:'#fca5a5', row:5, nianHao:'初元', personal:'劉奭', wikiEn:'Emperor_Yuan_of_Han' },
  { name:'成帝', en:'Emperor Cheng of Han',
    start:-33,  end:-7,   color:'#dc2626', row:5, nianHao:'建始', personal:'劉驁', wikiEn:'Emperor_Cheng_of_Han' },
  { name:'哀帝', en:'Emperor Ai of Han',
    start:-7,   end:-1,   color:'#ef4444', row:5, nianHao:'建平', personal:'劉欣', wikiEn:'Emperor_Ai_of_Han' },
  { name:'平帝', en:'Emperor Ping of Han',
    start:-1,   end:6,    color:'#f87171', row:5, nianHao:'元始', personal:'劉衎', wikiEn:'Emperor_Ping_of_Han' },
  { name:'孺子嬰', en:'Ruzi Ying',
    start:6,    end:9,    color:'#fca5a5', row:5, personal:'劉嬰' },

  // ══ 東漢（25 ~ 220）══════════════════════════════════════════════
  // 循環色：['#c2410c','#ea580c','#f97316','#fb923c']
  { name:'光武帝', en:'Emperor Guangwu – founder of Eastern Han',
    start:25,   end:57,   color:'#c2410c', row:5, nianHao:'建武', personal:'劉秀', wikiEn:'Emperor_Guangwu_of_Han' },
  { name:'明帝', en:'Emperor Ming of Han',
    start:57,   end:75,   color:'#ea580c', row:5, nianHao:'永平', personal:'劉莊', wikiEn:'Emperor_Ming_of_Han' },
  { name:'章帝', en:'Emperor Zhang of Han',
    start:75,   end:88,   color:'#f97316', row:5, nianHao:'建初', personal:'劉炟', wikiEn:'Emperor_Zhang_of_Han' },
  { name:'和帝', en:'Emperor He of Han',
    start:88,   end:106,  color:'#fb923c', row:5, nianHao:'永元', personal:'劉肇', wikiEn:'Emperor_He_of_Han' },
  { name:'安帝', en:'Emperor An of Han',
    start:106,  end:125,  color:'#c2410c', row:5, nianHao:'永初', personal:'劉祜', wikiEn:'Emperor_An_of_Han' },
  { name:'順帝', en:'Emperor Shun of Han',
    start:125,  end:144,  color:'#ea580c', row:5, nianHao:'永建', personal:'劉保', wikiEn:'Emperor_Shun_of_Han' },
  { name:'沖帝', en:'Emperor Chong of Han',
    start:144,  end:145,  color:'#f97316', row:5, nianHao:'永嘉', personal:'劉炳' },
  { name:'質帝', en:'Emperor Zhi of Han',
    start:145,  end:146,  color:'#fb923c', row:5, nianHao:'本初', personal:'劉纘' },
  { name:'桓帝', en:'Emperor Huan of Han',
    start:146,  end:168,  color:'#c2410c', row:5, nianHao:'建和', personal:'劉志', wikiEn:'Emperor_Huan_of_Han' },
  { name:'靈帝', en:'Emperor Ling of Han',
    start:168,  end:189,  color:'#ea580c', row:5, nianHao:'建寧', personal:'劉宏', wikiEn:'Emperor_Ling_of_Han' },
  { name:'獻帝', en:'Emperor Xian of Han – last Han emperor',
    start:189,  end:220,  color:'#f97316', row:5, nianHao:'初平', personal:'劉協', wikiEn:'Emperor_Xian_of_Han' },

  // ══ 唐（618 ~ 907）════════════════════════════════════════════════
  // 循環色：['#92400e','#b45309','#d97706','#fcd34d']
  { name:'高祖', en:'Emperor Gaozu of Tang – founder',
    start:618,  end:626,  color:'#92400e', row:5, nianHao:'武德', personal:'李淵', wikiEn:'Emperor_Gaozu_of_Tang' },
  { name:'太宗', en:'Emperor Taizong of Tang – Zhenguan Reign',
    start:626,  end:649,  color:'#b45309', row:5, nianHao:'貞觀', personal:'李世民', wikiEn:'Emperor_Taizong_of_Tang' },
  { name:'高宗', en:'Emperor Gaozong of Tang',
    start:649,  end:683,  color:'#d97706', row:5, nianHao:'永徽', personal:'李治', wikiEn:'Emperor_Gaozong_of_Tang' },
  { name:'中宗', en:'Emperor Zhongzong (first reign)',
    start:684,  end:685,  color:'#fcd34d', row:5, nianHao:'嗣聖', personal:'李顯' },
  { name:'武則天', en:'Empress Wu Zetian – only female emperor of China',
    start:690,  end:705,  color:'#92400e', row:5, nianHao:'天授', personal:'武曌', wikiEn:'Wu_Zetian' },
  { name:'中宗（復）', en:'Emperor Zhongzong (restored)',
    start:705,  end:710,  color:'#b45309', row:5, nianHao:'神龍', personal:'李顯' },
  { name:'睿宗', en:'Emperor Ruizong of Tang',
    start:710,  end:712,  color:'#d97706', row:5, nianHao:'景雲', personal:'李旦', wikiEn:'Emperor_Ruizong_of_Tang' },
  { name:'玄宗', en:'Emperor Xuanzong of Tang – Kaiyuan golden age',
    start:712,  end:756,  color:'#fcd34d', row:5, nianHao:'開元', personal:'李隆基', wikiEn:'Emperor_Xuanzong_of_Tang' },
  { name:'肅宗', en:'Emperor Suzong of Tang',
    start:756,  end:762,  color:'#92400e', row:5, nianHao:'至德', personal:'李亨', wikiEn:'Emperor_Suzong_of_Tang' },
  { name:'代宗', en:'Emperor Daizong of Tang',
    start:762,  end:779,  color:'#b45309', row:5, nianHao:'寶應', personal:'李豫', wikiEn:'Emperor_Daizong_of_Tang' },
  { name:'德宗', en:'Emperor Dezong of Tang',
    start:779,  end:805,  color:'#d97706', row:5, nianHao:'建中', personal:'李適', wikiEn:'Emperor_Dezong_of_Tang' },
  { name:'憲宗', en:'Emperor Xianzong of Tang',
    start:805,  end:820,  color:'#fcd34d', row:5, nianHao:'元和', personal:'李純', wikiEn:'Emperor_Xianzong_of_Tang' },
  { name:'穆宗', en:'Emperor Muzong of Tang',
    start:820,  end:824,  color:'#92400e', row:5, nianHao:'長慶', personal:'李恆', wikiEn:'Emperor_Muzong_of_Tang' },
  { name:'敬宗', en:'Emperor Jingzong of Tang',
    start:824,  end:827,  color:'#b45309', row:5, nianHao:'寶曆', personal:'李湛' },
  { name:'文宗', en:'Emperor Wenzong of Tang',
    start:827,  end:840,  color:'#d97706', row:5, nianHao:'大和', personal:'李昂', wikiEn:'Emperor_Wenzong_of_Tang' },
  { name:'武宗', en:'Emperor Wuzong of Tang – Huichang Suppression of Buddhism',
    start:840,  end:846,  color:'#fcd34d', row:5, nianHao:'會昌', personal:'李炎', wikiEn:'Emperor_Wuzong_of_Tang' },
  { name:'宣宗', en:'Emperor Xuanzong (the Great) of Tang',
    start:846,  end:859,  color:'#92400e', row:5, nianHao:'大中', personal:'李忱', wikiEn:'Emperor_Xuanzong_of_Tang_(II)' },
  { name:'懿宗', en:'Emperor Yizong of Tang',
    start:859,  end:873,  color:'#b45309', row:5, nianHao:'咸通', personal:'李漼', wikiEn:'Emperor_Yizong_of_Tang' },
  { name:'僖宗', en:'Emperor Xizong of Tang',
    start:873,  end:888,  color:'#d97706', row:5, nianHao:'乾符', personal:'李儇', wikiEn:'Emperor_Xizong_of_Tang' },
  { name:'昭宗', en:'Emperor Zhaozong of Tang',
    start:888,  end:904,  color:'#fcd34d', row:5, nianHao:'龍紀', personal:'李曄', wikiEn:'Emperor_Zhaozong_of_Tang' },
  { name:'哀帝', en:'Emperor Ai of Tang – last Tang emperor',
    start:904,  end:907,  color:'#92400e', row:5, nianHao:'天祐', personal:'李柷', wikiEn:'Emperor_Ai_of_Tang' },

  // ══ 北宋（960 ~ 1127）══════════════════════════════════════════════
  // 循環色：['#9a3412','#c2410c','#ea580c','#f97316']
  { name:'太祖', en:'Emperor Taizu of Song – founder',
    start:960,  end:976,  color:'#9a3412', row:5, nianHao:'建隆', personal:'趙匡胤', wikiEn:'Emperor_Taizu_of_Song' },
  { name:'太宗', en:'Emperor Taizong of Song',
    start:976,  end:997,  color:'#c2410c', row:5, nianHao:'太平興國', personal:'趙光義', wikiEn:'Emperor_Taizong_of_Song' },
  { name:'真宗', en:'Emperor Zhenzong of Song',
    start:997,  end:1022, color:'#ea580c', row:5, nianHao:'咸平', personal:'趙恆', wikiEn:'Emperor_Zhenzong_of_Song' },
  { name:'仁宗', en:'Emperor Renzong of Song – longest reign in Song',
    start:1022, end:1063, color:'#f97316', row:5, nianHao:'天聖', personal:'趙禎', wikiEn:'Emperor_Renzong_of_Song' },
  { name:'英宗', en:'Emperor Yingzong of Song',
    start:1063, end:1067, color:'#9a3412', row:5, nianHao:'治平', personal:'趙曙', wikiEn:'Emperor_Yingzong_of_Song' },
  { name:'神宗', en:'Emperor Shenzong of Song – Wang Anshi reforms',
    start:1067, end:1085, color:'#c2410c', row:5, nianHao:'熙寧', personal:'趙頊', wikiEn:'Emperor_Shenzong_of_Song' },
  { name:'哲宗', en:'Emperor Zhezong of Song',
    start:1085, end:1100, color:'#ea580c', row:5, nianHao:'元祐', personal:'趙煦', wikiEn:'Emperor_Zhezong_of_Song' },
  { name:'徽宗', en:'Emperor Huizong of Song – poet emperor, captured by Jurchen',
    start:1100, end:1125, color:'#f97316', row:5, nianHao:'崇寧', personal:'趙佶', wikiEn:'Emperor_Huizong_of_Song' },
  { name:'欽宗', en:'Emperor Qinzong of Song – Jingkang Incident',
    start:1125, end:1127, color:'#9a3412', row:5, nianHao:'靖康', personal:'趙桓', wikiEn:'Emperor_Qinzong_of_Song' },

  // ══ 南宋（1127 ~ 1279）═════════════════════════════════════════════
  // 循環色：['#78350f','#92400e','#b45309','#d97706']
  { name:'高宗', en:'Emperor Gaozong of Song – founder of Southern Song',
    start:1127, end:1162, color:'#78350f', row:5, nianHao:'建炎', personal:'趙構', wikiEn:'Emperor_Gaozong_of_Song' },
  { name:'孝宗', en:'Emperor Xiaozong of Song',
    start:1162, end:1189, color:'#92400e', row:5, nianHao:'隆興', personal:'趙昚', wikiEn:'Emperor_Xiaozong_of_Song' },
  { name:'光宗', en:'Emperor Guangzong of Song',
    start:1189, end:1194, color:'#b45309', row:5, nianHao:'紹熙', personal:'趙惇', wikiEn:'Emperor_Guangzong_of_Song' },
  { name:'寧宗', en:'Emperor Ningzong of Song',
    start:1194, end:1224, color:'#d97706', row:5, nianHao:'慶元', personal:'趙擴', wikiEn:'Emperor_Ningzong_of_Song' },
  { name:'理宗', en:'Emperor Lizong of Song',
    start:1224, end:1264, color:'#78350f', row:5, nianHao:'寶慶', personal:'趙昀', wikiEn:'Emperor_Lizong_of_Song' },
  { name:'度宗', en:'Emperor Duzong of Song',
    start:1264, end:1274, color:'#92400e', row:5, nianHao:'咸淳', personal:'趙禥', wikiEn:'Emperor_Duzong_of_Song' },
  { name:'恭帝', en:'Emperor Gong of Song',
    start:1274, end:1276, color:'#b45309', row:5, nianHao:'德祐', personal:'趙㬎' },
  { name:'端宗', en:'Emperor Duanzong of Song',
    start:1276, end:1278, color:'#d97706', row:5, nianHao:'景炎', personal:'趙昰', wikiEn:'Emperor_Duanzong_of_Song' },
  { name:'懷宗', en:'Emperor Huaizong of Song – last Song emperor (drowned at Yamen)',
    start:1278, end:1279, color:'#78350f', row:5, nianHao:'祥興', personal:'趙昺', wikiEn:'Emperor_Bing_of_Song' },

  // ══ 明（1368 ~ 1644）══════════════════════════════════════════════
  // 循環色：['#7f1d1d','#991b1b','#b91c1c','#dc2626']
  { name:'太祖', en:'Hongwu Emperor – founder of Ming',
    start:1368, end:1398, color:'#7f1d1d', row:5, nianHao:'洪武', personal:'朱元璋', wikiEn:'Hongwu_Emperor' },
  { name:'惠宗', en:'Jianwen Emperor',
    start:1398, end:1402, color:'#991b1b', row:5, nianHao:'建文', personal:'朱允炆', wikiEn:'Jianwen_Emperor' },
  { name:'成祖', en:'Yongle Emperor – moved capital to Beijing',
    start:1402, end:1424, color:'#b91c1c', row:5, nianHao:'永樂', personal:'朱棣', wikiEn:'Yongle_Emperor' },
  { name:'仁宗', en:'Hongxi Emperor',
    start:1424, end:1425, color:'#dc2626', row:5, nianHao:'洪熙', personal:'朱高熾', wikiEn:'Hongxi_Emperor' },
  { name:'宣宗', en:'Xuande Emperor – Xuande golden age',
    start:1425, end:1435, color:'#7f1d1d', row:5, nianHao:'宣德', personal:'朱瞻基', wikiEn:'Xuande_Emperor' },
  { name:'英宗', en:'Zhengtong Emperor (first reign) – captured by Mongols',
    start:1435, end:1449, color:'#991b1b', row:5, nianHao:'正統', personal:'朱祁鎮', wikiEn:'Zhengtong_Emperor' },
  { name:'代宗', en:'Jingtai Emperor – defended Beijing from Mongols',
    start:1449, end:1457, color:'#b91c1c', row:5, nianHao:'景泰', personal:'朱祁鈺', wikiEn:'Jingtai_Emperor' },
  { name:'英宗（復）', en:'Tianshun Emperor (restored reign)',
    start:1457, end:1464, color:'#dc2626', row:5, nianHao:'天順', personal:'朱祁鎮', wikiEn:'Zhengtong_Emperor' },
  { name:'憲宗', en:'Chenghua Emperor',
    start:1464, end:1487, color:'#7f1d1d', row:5, nianHao:'成化', personal:'朱見深', wikiEn:'Chenghua_Emperor' },
  { name:'孝宗', en:'Hongzhi Emperor – benevolent rule',
    start:1487, end:1505, color:'#991b1b', row:5, nianHao:'弘治', personal:'朱祐樘', wikiEn:'Hongzhi_Emperor' },
  { name:'武宗', en:'Zhengde Emperor',
    start:1505, end:1521, color:'#b91c1c', row:5, nianHao:'正德', personal:'朱厚照', wikiEn:'Zhengde_Emperor' },
  { name:'世宗', en:'Jiajing Emperor – 45-year reign, Daoist recluse',
    start:1521, end:1566, color:'#dc2626', row:5, nianHao:'嘉靖', personal:'朱厚熜', wikiEn:'Jiajing_Emperor' },
  { name:'穆宗', en:'Longqing Emperor',
    start:1566, end:1572, color:'#7f1d1d', row:5, nianHao:'隆慶', personal:'朱載坖', wikiEn:'Longqing_Emperor' },
  { name:'神宗', en:'Wanli Emperor – 48-year reign, later recluse',
    start:1572, end:1620, color:'#991b1b', row:5, nianHao:'萬曆', personal:'朱翊鈞', wikiEn:'Wanli_Emperor' },
  { name:'光宗', en:'Taichang Emperor – died after one month',
    start:1620, end:1621, color:'#b91c1c', row:5, nianHao:'泰昌', personal:'朱常洛', wikiEn:'Taichang_Emperor' },
  { name:'熹宗', en:'Tianqi Emperor – Wei Zhongxian eunuch power',
    start:1621, end:1627, color:'#dc2626', row:5, nianHao:'天啟', personal:'朱由校', wikiEn:'Tianqi_Emperor' },
  { name:'思宗', en:'Chongzhen Emperor – last Ming emperor, died defending Beijing',
    start:1627, end:1644, color:'#7f1d1d', row:5, nianHao:'崇禎', personal:'朱由檢', wikiEn:'Chongzhen_Emperor' },

  // ══ 清（1644 ~ 1912）══════════════════════════════════════════════
  // 循環色：['#78350f','#92400e','#a16207','#ca8a04']
  { name:'世祖', en:'Shunzhi Emperor – first Qing emperor to rule China proper',
    start:1644, end:1661, color:'#78350f', row:5, nianHao:'順治', personal:'福臨', wikiEn:'Shunzhi_Emperor' },
  { name:'聖祖', en:'Kangxi Emperor – 61-year reign, longest in Chinese history',
    start:1661, end:1722, color:'#92400e', row:5, nianHao:'康熙', personal:'玄燁', wikiEn:'Kangxi_Emperor' },
  { name:'世宗', en:'Yongzheng Emperor – administrative reforms',
    start:1722, end:1735, color:'#a16207', row:5, nianHao:'雍正', personal:'胤禛', wikiEn:'Yongzheng_Emperor' },
  { name:'高宗', en:'Qianlong Emperor – 60-year reign at peak of Qing power',
    start:1735, end:1796, color:'#ca8a04', row:5, nianHao:'乾隆', personal:'弘曆', wikiEn:'Qianlong_Emperor' },
  { name:'仁宗', en:'Jiaqing Emperor',
    start:1796, end:1820, color:'#78350f', row:5, nianHao:'嘉慶', personal:'顒琰', wikiEn:'Jiaqing_Emperor' },
  { name:'宣宗', en:'Daoguang Emperor – First Opium War',
    start:1820, end:1850, color:'#92400e', row:5, nianHao:'道光', personal:'旻寧', wikiEn:'Daoguang_Emperor' },
  { name:'文宗', en:'Xianfeng Emperor – Second Opium War, Taiping Rebellion',
    start:1850, end:1861, color:'#a16207', row:5, nianHao:'咸豐', personal:'奕詝', wikiEn:'Xianfeng_Emperor' },
  { name:'穆宗', en:'Tongzhi Emperor – ruled under Empress Dowager Cixi',
    start:1861, end:1875, color:'#ca8a04', row:5, nianHao:'同治', personal:'載淳', wikiEn:'Tongzhi_Emperor' },
  { name:'德宗', en:'Guangxu Emperor – Hundred Days Reform, controlled by Cixi',
    start:1875, end:1908, color:'#78350f', row:5, nianHao:'光緒', personal:'載湉', wikiEn:'Guangxu_Emperor' },
  { name:'宣統帝', en:'Xuantong Emperor (Puyi) – last emperor of China',
    start:1908, end:1912, color:'#92400e', row:5, nianHao:'宣統', personal:'溥儀', wikiEn:'Puyi' },
];
