// 春秋戰國：主要諸侯國君主
// Row 6=齊, 7=晉, 8=宋, 9=秦（諸侯）, 10=楚
// 西周前期年份為學術估算

const ZH_STATES = [

  // ═══ ROW 6  齊國（-1046 ~ -221）════════════════════════════════════════
  // 姜姓呂氏 → 田氏代齊（-386）色系：綠
  { name:'太公望', en:'Jiang Shang (Lü Wang) – founder of Qi; Zhou\'s Grand Strategist; 封國元祖', start:-1046, end:-1015, color:'#4ade80', row:6, personal:'姜尚', wikiEn:'Jiang_Ziya' },
  { name:'丁公',   en:'Duke Ding of Qi',                                     start:-1015, end:-976,  color:'#86efac', row:6, personal:'姜伋' },
  { name:'乙公',   en:'Duke Yi of Qi',                                       start:-975,  end:-944,  color:'#22c55e', row:6, personal:'姜得' },
  { name:'癸公',   en:'Duke Gui of Qi – long reign',                         start:-943,  end:-895,  color:'#15803d', row:6, personal:'姜慈母' },
  { name:'哀公',   en:'Duke Ai of Qi – boiled alive by Zhou King Yiwang',    start:-894,  end:-879,  color:'#4ade80', row:6, personal:'姜不辰' },
  { name:'胡公',   en:'Duke Hu of Qi',                                       start:-878,  end:-861,  color:'#86efac', row:6, personal:'姜靜' },
  { name:'獻公',   en:'Duke Xian of Qi – moved capital to Linzi (臨淄)',     start:-860,  end:-851,  color:'#22c55e', row:6, personal:'姜山' },
  { name:'武公',   en:'Duke Wu of Qi',                                       start:-850,  end:-825,  color:'#15803d', row:6, personal:'姜壽' },
  { name:'厲公',   en:'Duke Li of Qi',                                       start:-824,  end:-815,  color:'#4ade80', row:6, personal:'姜無忌' },
  { name:'文公',   en:'Duke Wen of Qi',                                      start:-814,  end:-804,  color:'#86efac', row:6, personal:'姜赤' },
  { name:'成公',   en:'Duke Cheng of Qi',                                    start:-803,  end:-795,  color:'#22c55e', row:6, personal:'姜說' },
  { name:'莊公',   en:'Duke Zhuang I of Qi – ~64-year reign',               start:-794,  end:-731,  color:'#15803d', row:6, personal:'姜購' },
  { name:'釐公',   en:'Duke Xi of Qi',                                       start:-730,  end:-698,  color:'#4ade80', row:6, personal:'姜祿甫' },
  { name:'襄公',   en:'Duke Xiang of Qi – murdered Lu\'s Duke Huan; killed by cousin in coup', start:-697, end:-686, color:'#86efac', row:6, personal:'姜諸兒' },
  { name:'桓公',   en:'Duke Huan of Qi – 1st Spring & Autumn hegemon; PM Guan Zhong; 尊王攘夷', start:-685, end:-643, color:'#22c55e', row:6, personal:'姜小白', wikiEn:'Duke_Huan_of_Qi' },
  { name:'孝公',   en:'Duke Xiao of Qi',                                     start:-642,  end:-633,  color:'#15803d', row:6, personal:'姜昭' },
  { name:'昭公',   en:'Duke Zhao of Qi',                                     start:-632,  end:-613,  color:'#4ade80', row:6, personal:'姜潘' },
  { name:'懿公',   en:'Duke Yi of Qi – killed by charioteers in revenge',    start:-612,  end:-609,  color:'#86efac', row:6, personal:'姜商人' },
  { name:'惠公',   en:'Duke Hui of Qi',                                      start:-608,  end:-599,  color:'#22c55e', row:6, personal:'姜元' },
  { name:'頃公',   en:'Duke Qing of Qi – defeated by Jin at Battle of An -589', start:-598, end:-582, color:'#15803d', row:6, personal:'姜無野' },
  { name:'靈公',   en:'Duke Ling of Qi',                                     start:-581,  end:-554,  color:'#4ade80', row:6, personal:'姜環' },
  { name:'莊公',   en:'Duke Zhuang II of Qi – assassinated by minister Cui Zhu (崔杼)', start:-553, end:-548, color:'#86efac', row:6, personal:'姜光' },
  { name:'景公',   en:'Duke Jing of Qi – 57-year reign; minister Yanzi (晏嬰) famed diplomat', start:-547, end:-490, color:'#22c55e', row:6, personal:'姜杵臼', wikiEn:'Duke_Jing_of_Qi' },
  { name:'晏孺子', en:'Child ruler – quickly deposed and killed',            start:-489,  end:-488,  color:'#15803d', row:6, personal:'姜荼' },
  { name:'悼公',   en:'Duke Dao of Qi',                                      start:-488,  end:-485,  color:'#4ade80', row:6, personal:'姜陽生' },
  { name:'簡公',   en:'Duke Jian of Qi – Tian Chengzi seized power; duke killed -481', start:-484, end:-481, color:'#86efac', row:6, personal:'姜壬' },
  { name:'平公',   en:'Duke Ping of Qi',                                     start:-480,  end:-456,  color:'#22c55e', row:6, personal:'姜驁' },
  { name:'宣公',   en:'Duke Xuan of Qi (Jiang surname)',                     start:-455,  end:-404,  color:'#15803d', row:6, personal:'姜積' },
  { name:'康公',   en:'Duke Kang of Qi – last Jiang ruler; exiled by Tian He', start:-403, end:-379, color:'#4ade80', row:6, personal:'姜貸' },
  // 田齊 ──────────────────────────────────────────────────────────────────
  { name:'田和',   en:'Tian He – first Tian ruler; recognized by Zhou king -386; died -384', start:-386, end:-384, color:'#86efac', row:6, personal:'田和' },
  { name:'齊侯剡', en:'Tian Jian – killed by brother Tian Wu',               start:-383,  end:-375,  color:'#22c55e', row:6, personal:'田剡' },
  { name:'田午',   en:'Tian Wu (Duke Huan of Tian Qi) – founded 稷下學宮 (Jixia Academy)', start:-374, end:-357, color:'#15803d', row:6, personal:'田午' },
  { name:'威王',   en:'King Wei of Qi – golden age; 稷下學宮 peak; Sun Bin defeated Wei at 桂陵/馬陵', start:-356, end:-320, color:'#4ade80', row:6, personal:'田因齊', wikiEn:'King_Wei_of_Qi' },
  { name:'宣王',   en:'King Xuan of Qi – Mencius visited; attacked Yan -314; largest scholarly court', start:-319, end:-301, color:'#86efac', row:6, personal:'田辟彊' },
  { name:'湣王',   en:'King Min of Qi – conquered Yan -314; then nearly destroyed by 樂毅\'s 5-state coalition -284', start:-300, end:-284, color:'#22c55e', row:6, personal:'田地' },
  { name:'襄王',   en:'King Xiang of Qi – fled exile; 田單\'s fire-ox strategy (火牛陣) restored Qi', start:-283, end:-265, color:'#15803d', row:6, personal:'田法章' },
  { name:'王建',   en:'King Jian of Qi – surrendered to Qin without a fight -221; starved in pine grove', start:-264, end:-221, color:'#4ade80', row:6, personal:'田建', wikiEn:'King_Jian_of_Qi' },

  // ═══ ROW 7  晉國（-1033 ~ -375）════════════════════════════════════════
  // 原名 唐（唐叔虞），子燮遷晉水改名晉  色系：藍
  { name:'唐叔虞', en:'Shu Yu of Tang – founder; given Tang (later Jin) by King Wu of Zhou', start:-1033, end:-1016, color:'#60a5fa', row:7, personal:'姬虞', wikiEn:'Shu_Yu_of_Tang' },
  { name:'燮',     en:'Xie of Jin – renamed state Tang → Jin after moving to the Jin River valley', start:-1015, end:-988, color:'#93c5fd', row:7, personal:'姬燮' },
  { name:'武侯',   en:'Duke Wu of Jin',                                      start:-987,  end:-967,  color:'#3b82f6', row:7, personal:'姬寧族' },
  { name:'成侯',   en:'Duke Cheng of Jin',                                   start:-966,  end:-940,  color:'#1d4ed8', row:7, personal:'姬服人' },
  { name:'厲侯',   en:'Duke Li of Jin (early)',                              start:-939,  end:-901,  color:'#60a5fa', row:7, personal:'姬福' },
  { name:'靖侯',   en:'Duke Jing of Jin',                                    start:-900,  end:-873,  color:'#93c5fd', row:7, personal:'姬宜臼' },
  { name:'釐侯',   en:'Duke Xi of Jin',                                      start:-872,  end:-853,  color:'#3b82f6', row:7, personal:'姬司徒' },
  { name:'獻侯',   en:'Duke Xian of Jin I – 曲沃 rival branch began arising', start:-852, end:-841,  color:'#1d4ed8', row:7, personal:'姬籍' },
  { name:'穆侯',   en:'Duke Mu of Jin – fought western barbarians',          start:-840,  end:-823,  color:'#60a5fa', row:7, personal:'姬費王' },
  { name:'殤叔',   en:'Duke Shang Shu – usurped throne 4 years; killed by 文侯', start:-822, end:-818, color:'#93c5fd', row:7, personal:'姬殤叔' },
  { name:'文侯',   en:'Duke Wen of Jin (仇) – escorted Zhou Ping Wang eastward; restored Zhou order', start:-817, end:-785, color:'#3b82f6', row:7, personal:'姬仇' },
  { name:'昭侯',   en:'Duke Zhao of Jin – enfeoffed uncle at 曲沃, creating 100-year civil war', start:-784, end:-766, color:'#1d4ed8', row:7, personal:'姬伯' },
  { name:'孝侯',   en:'Duke Xiao of Jin – killed by 曲沃',                  start:-765,  end:-751,  color:'#60a5fa', row:7, personal:'姬平' },
  { name:'鄂侯',   en:'Duke E of Jin',                                       start:-750,  end:-741,  color:'#93c5fd', row:7, personal:'姬鄂' },
  { name:'哀侯',   en:'Duke Ai of Jin – captured and killed by 曲沃',        start:-740,  end:-725,  color:'#3b82f6', row:7, personal:'姬光' },
  { name:'小子侯', en:'Duke Xiaozi of Jin – killed by 曲沃莊伯',            start:-724,  end:-718,  color:'#1d4ed8', row:7, personal:'姬小子' },
  { name:'侯緡',   en:'Duke Min of Jin (晉侯緡) – killed -679 by 曲沃武公 who finally unified Jin', start:-717, end:-679, color:'#60a5fa', row:7, personal:'姬緡' },
  { name:'武公',   en:'Duke Wu of Jin – unified Jin; first fully sovereign Jin duke',   start:-678, end:-677,  color:'#93c5fd', row:7, personal:'姬稱' },
  { name:'獻公',   en:'Duke Xian of Jin – 假道伐虢 destroyed Guo & Yu; Li Ji (驪姬) succession crisis', start:-676, end:-651, color:'#3b82f6', row:7, personal:'姬詭諸', wikiEn:'Duke_Xian_of_Jin' },
  { name:'惠公',   en:'Duke Hui of Jin – rival of Chong Er; defeated at Battle of Han -645', start:-650, end:-637, color:'#1d4ed8', row:7, personal:'姬夷吾' },
  { name:'懷公',   en:'Duke Huai of Jin – brief reign; killed when Chong Er returned', start:-637, end:-636, color:'#60a5fa', row:7, personal:'姬圉' },
  { name:'文公',   en:'Duke Wen of Jin (重耳) – Spring & Autumn hegemon; 退避三舍; won Battle of Chengpu -632', start:-636, end:-628, color:'#93c5fd', row:7, personal:'姬重耳', wikiEn:'Duke_Wen_of_Jin' },
  { name:'襄公',   en:'Duke Xiang of Jin – ambushed and annihilated Qin army at 殽之戰 -627',   start:-627, end:-621, color:'#3b82f6', row:7, personal:'姬歡' },
  { name:'靈公',   en:'Duke Ling of Jin – tyrannical; shot at subjects from tower; assassinated by Zhao Dun', start:-620, end:-607, color:'#1d4ed8', row:7, personal:'姬夷皋' },
  { name:'成公',   en:'Duke Cheng of Jin',                                   start:-606,  end:-600,  color:'#60a5fa', row:7, personal:'姬黑臀' },
  { name:'景公',   en:'Duke Jing of Jin – Battle of An (鞌之戰) vs Qi -589; drowned in privy', start:-599, end:-581, color:'#93c5fd', row:7, personal:'姬據' },
  { name:'厲公',   en:'Duke Li of Jin – tried to curb noble power; murdered by noble clans', start:-580, end:-573, color:'#3b82f6', row:7, personal:'姬壽曼' },
  { name:'悼公',   en:'Duke Dao of Jin – restored Jin hegemony with 六卿聯盟; 弭兵之盟 era', start:-572, end:-558, color:'#1d4ed8', row:7, personal:'姬周', wikiEn:'Duke_Dao_of_Jin' },
  { name:'平公',   en:'Duke Ping of Jin – 弭兵之盟 (Song peace conference) -546; Jin-Chu split hegemony', start:-557, end:-532, color:'#60a5fa', row:7, personal:'姬彪' },
  { name:'昭公',   en:'Duke Zhao of Jin',                                    start:-531,  end:-526,  color:'#93c5fd', row:7, personal:'姬夷' },
  { name:'頃公',   en:'Duke Qing of Jin',                                    start:-525,  end:-512,  color:'#3b82f6', row:7, personal:'姬去疾' },
  { name:'定公',   en:'Duke Ding of Jin – Three Families (韓/趙/魏) grew dominant',  start:-511, end:-475, color:'#1d4ed8', row:7, personal:'姬午' },
  { name:'出公',   en:'Duke Chu of Jin – Three Families effectively controlled Jin territory', start:-474, end:-452, color:'#60a5fa', row:7, personal:'姬鑿' },
  { name:'哀公',   en:'Duke Ai of Jin',                                      start:-451,  end:-434,  color:'#93c5fd', row:7, personal:'姬驕' },
  { name:'幽公',   en:'Duke You of Jin – nominal ruler; Jin smaller than the Three Families', start:-433, end:-416, color:'#3b82f6', row:7, personal:'姬柳' },
  { name:'烈公',   en:'Duke Lie of Jin',                                     start:-415,  end:-389,  color:'#1d4ed8', row:7, personal:'姬止' },
  { name:'孝公',   en:'Duke Xiao of Jin',                                    start:-388,  end:-377,  color:'#60a5fa', row:7, personal:'姬頎' },
  { name:'靜公',   en:'Duke Jing of Jin – last ruler; Jin extinguished by Han and Wei -376', start:-376, end:-375, color:'#93c5fd', row:7, personal:'姬俱酒' },

  // ═══ ROW 8  宋國（-1046 ~ -286）════════════════════════════════════════
  // 殷商後裔，「亡國之餘，不可責以周禮」 色系：紫
  { name:'微子啟', en:'Wei Zi Qi – founder; Shang royal descendant; given Song to continue Shang sacrifices', start:-1046, end:-1025, color:'#c084fc', row:8, personal:'子啟', wikiEn:'Wei_Zi' },
  { name:'微仲',   en:'Wei Zhong – 2nd ruler of Song',                       start:-1025, end:-1004, color:'#d8b4fe', row:8, personal:'子衍' },
  { name:'宋公稽', en:'Duke Ji of Song',                                     start:-1003, end:-983,  color:'#a855f7', row:8, personal:'子稽' },
  { name:'丁公',   en:'Duke Ding of Song',                                   start:-982,  end:-952,  color:'#7c3aed', row:8, personal:'子申' },
  { name:'湣公共', en:'Duke Min Gong – very long reign',                     start:-951,  end:-906,  color:'#c084fc', row:8, personal:'子共' },
  { name:'煬公',   en:'Duke Yang – killed by brother who seized throne',     start:-905,  end:-900,  color:'#d8b4fe', row:8, personal:'子熙' },
  { name:'厲公',   en:'Duke Li of Song',                                     start:-899,  end:-859,  color:'#a855f7', row:8, personal:'子鮒祀' },
  { name:'釐公',   en:'Duke Xi of Song',                                     start:-858,  end:-831,  color:'#7c3aed', row:8, personal:'子舉' },
  { name:'惠公',   en:'Duke Hui of Song',                                    start:-830,  end:-801,  color:'#c084fc', row:8, personal:'子覸' },
  { name:'哀公',   en:'Duke Ai of Song',                                     start:-800,  end:-771,  color:'#d8b4fe', row:8, personal:'子' },
  { name:'戴公',   en:'Duke Dai – Kong Fuia (孔父嘉, Confucius\'s ancestor) served as minister', start:-770, end:-748, color:'#a855f7', row:8, personal:'子白' },
  { name:'武公',   en:'Duke Wu of Song',                                     start:-747,  end:-729,  color:'#7c3aed', row:8, personal:'子司空' },
  { name:'宣公',   en:'Duke Xuan – passed throne to brother Mupu (not son), causing later civil war', start:-728, end:-720, color:'#c084fc', row:8, personal:'子力' },
  { name:'穆公',   en:'Duke Mu – honored brother\'s wish; returned throne to Xuan\'s son (殤公)', start:-719, end:-710, color:'#d8b4fe', row:8, personal:'子和' },
  { name:'殤公',   en:'Duke Shang – 10 years of wars with Zheng; killed by 南宮長萬 in revolt', start:-709, end:-693, color:'#a855f7', row:8, personal:'子與夷' },
  { name:'莊公',   en:'Duke Zhuang – installed after 南宮長萬\'s revolt was suppressed', start:-692, end:-683, color:'#7c3aed', row:8, personal:'子馮' },
  { name:'閔公',   en:'Duke Min – killed by 南宮長萬 (Nan Gong Changwan) in revolt', start:-682, end:-681, color:'#c084fc', row:8, personal:'子捷' },
  { name:'桓公',   en:'Duke Huan – restored order after civil war; 30-year stable reign', start:-681, end:-651, color:'#d8b4fe', row:8, personal:'子御說' },
  { name:'襄公',   en:'Duke Xiang – claimed hegemony; \"宋襄之仁\" at Battle of Hong -638; defeated by Chu', start:-650, end:-637, color:'#a855f7', row:8, personal:'子茲父', wikiEn:'Duke_Xiang_of_Song' },
  { name:'成公',   en:'Duke Cheng of Song',                                  start:-636,  end:-620,  color:'#7c3aed', row:8, personal:'子王臣' },
  { name:'昭公',   en:'Duke Zhao of Song',                                   start:-619,  end:-611,  color:'#c084fc', row:8, personal:'子杵臼' },
  { name:'文公',   en:'Duke Wen of Song',                                    start:-610,  end:-589,  color:'#d8b4fe', row:8, personal:'子鮑' },
  { name:'共公',   en:'Duke Gong of Song',                                   start:-588,  end:-576,  color:'#a855f7', row:8, personal:'子瑕' },
  { name:'平公',   en:'Duke Ping – 44-year reign; Song hosted 弭兵之盟 -546 (peace between Jin & Chu)', start:-575, end:-531, color:'#7c3aed', row:8, personal:'子成' },
  { name:'元公',   en:'Duke Yuan of Song',                                   start:-530,  end:-517,  color:'#c084fc', row:8, personal:'子佐' },
  { name:'景公',   en:'Duke Jing – 47-year reign; 景星 omen; 子罕 declined power', start:-516, end:-469, color:'#d8b4fe', row:8, personal:'子頭曼' },
  { name:'昭公',   en:'Duke Zhao of Song (later)',                           start:-468,  end:-422,  color:'#a855f7', row:8, personal:'子得' },
  { name:'悼公',   en:'Duke Dao of Song',                                    start:-421,  end:-414,  color:'#7c3aed', row:8, personal:'子購由' },
  { name:'休公',   en:'Duke Xiu of Song',                                    start:-413,  end:-391,  color:'#c084fc', row:8, personal:'子田' },
  { name:'辟公',   en:'Duke Pi of Song',                                     start:-390,  end:-383,  color:'#d8b4fe', row:8, personal:'子辟' },
  { name:'剔成君', en:'Ticheng Jun – usurped power; ruled 53 years; killed by brother (康王)',  start:-382, end:-329, color:'#a855f7', row:8, personal:'子齊' },
  { name:'康王',   en:'King Kang (偃) – tyrant (「東方桀」); Song destroyed by Qi/Wei/Chu coalition -286', start:-328, end:-286, color:'#7c3aed', row:8, personal:'子偃', wikiEn:'King_Kang_of_Song' },

  // ═══ ROW 9  秦國（諸侯）（-897 ~ -221）════════════════════════════════
  // 自非子獲封秦地 → 秦始皇統一  色系：橙
  { name:'非子',   en:'Feizi – given Qin as a small estate by Zhou King for horse-breeding excellence', start:-897, end:-858, color:'#fb923c', row:9, personal:'嬴非子' },
  { name:'秦侯',   en:'Qin Hou – 2nd Qin lord',                             start:-857,  end:-848,  color:'#fdba74', row:9, personal:'嬴' },
  { name:'公伯',   en:'Gong Bo – 3rd Qin lord',                             start:-847,  end:-845,  color:'#f97316', row:9, personal:'嬴公伯' },
  { name:'秦仲',   en:'Qin Zhong – Zhou ordered him to fight western Rong; died in battle -822', start:-844, end:-822, color:'#ea580c', row:9, personal:'嬴秦仲' },
  { name:'莊公',   en:'Duke Zhuang of Qin – avenged father; received land west of 犬丘',  start:-821, end:-778, color:'#fb923c', row:9, personal:'嬴其' },
  { name:'襄公',   en:'Duke Xiang of Qin – escorted Zhou east -771; first Qin Zhuhou (諸侯)', start:-777, end:-766, color:'#fdba74', row:9, personal:'嬴開', wikiEn:'Duke_Xiang_of_Qin' },
  { name:'文公',   en:'Duke Wen of Qin – 49-year reign; defeated Rong tribes, recovered Zhou ancestral land', start:-765, end:-716, color:'#f97316', row:9, personal:'嬴' },
  { name:'憲公',   en:'Duke Xian of Qin (寧公) – moved capital; extended Qin territory',   start:-715, end:-704, color:'#ea580c', row:9, personal:'嬴立' },
  { name:'出子',   en:'Duke Chu of Qin – child ruler; killed by大庶長弗忌 coup',           start:-703, end:-698, color:'#fb923c', row:9, personal:'嬴曼' },
  { name:'武公',   en:'Duke Wu of Qin – first to establish 縣 (county) system in conquered territories', start:-697, end:-678, color:'#fdba74', row:9, personal:'嬴說' },
  { name:'德公',   en:'Duke De of Qin – moved capital to 雍城; began 伏日 sacrifice',       start:-677, end:-676, color:'#f97316', row:9, personal:'嬴嘉' },
  { name:'宣公',   en:'Duke Xuan of Qin',                                    start:-675,  end:-664,  color:'#ea580c', row:9, personal:'嬴恬' },
  { name:'成公',   en:'Duke Cheng of Qin',                                   start:-663,  end:-660,  color:'#fb923c', row:9, personal:'嬴載' },
  { name:'穆公',   en:'Duke Mu of Qin – Spring & Autumn hegemon in the west; hired 百里奚; lost 殽之戰', start:-659, end:-621, color:'#fdba74', row:9, personal:'嬴任好', wikiEn:'Duke_Mu_of_Qin' },
  { name:'康公',   en:'Duke Kang of Qin',                                    start:-620,  end:-609,  color:'#f97316', row:9, personal:'嬴罃' },
  { name:'共公',   en:'Duke Gong of Qin',                                    start:-608,  end:-604,  color:'#ea580c', row:9, personal:'嬴稻' },
  { name:'桓公',   en:'Duke Huan of Qin',                                    start:-603,  end:-577,  color:'#fb923c', row:9, personal:'嬴榮' },
  { name:'景公',   en:'Duke Jing of Qin – 39-year reign; attended 弭兵之盟 -546',          start:-576, end:-537, color:'#fdba74', row:9, personal:'嬴石' },
  { name:'哀公',   en:'Duke Ai of Qin – aided Chu restoration after Wu invaded Ying (申包胥求秦兵)', start:-536, end:-501, color:'#f97316', row:9, personal:'嬴籍' },
  { name:'惠公',   en:'Duke Hui of Qin',                                     start:-500,  end:-491,  color:'#ea580c', row:9, personal:'嬴寧' },
  { name:'悼公',   en:'Duke Dao of Qin',                                     start:-490,  end:-477,  color:'#fb923c', row:9, personal:'嬴盤' },
  { name:'厲共公', en:'Duke Li Gong of Qin – long reign; first Qin contact with 義渠',    start:-476, end:-443, color:'#fdba74', row:9, personal:'嬴剛' },
  { name:'躁公',   en:'Duke Zao of Qin',                                     start:-442,  end:-429,  color:'#f97316', row:9, personal:'嬴' },
  { name:'懷公',   en:'Duke Huai of Qin – forced to commit suicide by nobles',             start:-428, end:-425, color:'#ea580c', row:9, personal:'嬴封' },
  { name:'靈公',   en:'Duke Ling of Qin – tried but failed to move capital back to 雍',    start:-424, end:-415, color:'#fb923c', row:9, personal:'嬴肅' },
  { name:'簡公',   en:'Duke Jian of Qin – introduced Left/Right Chancellor offices',       start:-414, end:-400, color:'#fdba74', row:9, personal:'嬴悼子' },
  { name:'惠公',   en:'Duke Hui of Qin II',                                  start:-399,  end:-387,  color:'#f97316', row:9, personal:'嬴仁' },
  { name:'出公',   en:'Duke Chu of Qin II – child ruler; killed by coup, 獻公 restored order', start:-386, end:-385, color:'#ea580c', row:9, personal:'嬴昌' },
  { name:'獻公',   en:'Duke Xian of Qin – moved capital to 栎阳; early reforms; defeated Wei at 石門', start:-384, end:-362, color:'#fb923c', row:9, personal:'嬴師隰', wikiEn:'Duke_Xian_of_Qin' },
  { name:'孝公',   en:'King Xiao of Qin – hired Shang Yang (商鞅); 商鞅變法 transformed Qin into a superpower', start:-361, end:-338, color:'#fdba74', row:9, personal:'嬴渠梁', wikiEn:'Duke_Xiao_of_Qin' },
  { name:'惠文王', en:'King Huiwen of Qin – first to call himself "王" (king); executed Shang Yang; conquered 巴蜀 -316', start:-337, end:-311, color:'#f97316', row:9, personal:'嬴駟', wikiEn:'King_Huiwen_of_Qin' },
  { name:'武王',   en:'King Wu of Qin – died lifting bronze tripod 龍文赤鼎; 甘茂 and 樗里疾 as ministers', start:-310, end:-307, color:'#ea580c', row:9, personal:'嬴蕩' },
  { name:'昭王',   en:'King Zhao of Qin (昭襄王) – 55-year reign; 范雎 and 白起; Battle of Changping -260; crushed Zhao', start:-306, end:-251, color:'#fb923c', row:9, personal:'嬴稷', wikiEn:'King_Zhaoxiang_of_Qin' },
  { name:'孝文王', en:'King Xiaowen of Qin – reigned only 3 days then died', start:-250,  end:-249,  color:'#fdba74', row:9, personal:'嬴柱' },
  { name:'莊襄王', en:'King Zhuangxiang of Qin – 呂不韋 as PM; Ying Zheng (future 始皇) born', start:-249, end:-247, color:'#f97316', row:9, personal:'嬴子楚' },
  { name:'王政',   en:'King Zheng of Qin → 秦始皇 – unified all 6 states -230 to -221; founded imperial China', start:-246, end:-221, color:'#ea580c', row:9, personal:'嬴政', wikiEn:'Qin_Shi_Huang' },

  // ═══ ROW 10  楚國（-1030 ~ -223）════════════════════════════════════════
  // 羋姓熊氏，「我蠻夷也」；首個自稱「王」的諸侯  色系：粉
  { name:'熊繹',   en:'Xiong Yi – founder; given lowest-rank (子) fief at Chu by Zhou; 跋山涉水以事天子', start:-1030, end:-1006, color:'#f472b6', row:10, personal:'熊繹' },
  { name:'熊艾',   en:'Xiong Ai',                                            start:-1005, end:-985,  color:'#f9a8d4', row:10, personal:'熊艾' },
  { name:'熊黵',   en:'Xiong Zhen',                                          start:-984,  end:-963,  color:'#ec4899', row:10, personal:'熊黵' },
  { name:'熊勝',   en:'Xiong Sheng',                                         start:-962,  end:-945,  color:'#be185d', row:10, personal:'熊勝' },
  { name:'熊楊',   en:'Xiong Yang',                                          start:-944,  end:-925,  color:'#f472b6', row:10, personal:'熊楊' },
  { name:'熊渠',   en:'Xiong Qu – called his three sons "kings" defying Zhou rank; later rescinded', start:-924, end:-905, color:'#f9a8d4', row:10, personal:'熊渠' },
  { name:'熊摯紅', en:'Xiong Zhi Hong',                                      start:-904,  end:-887,  color:'#ec4899', row:10, personal:'熊摯紅' },
  { name:'熊延',   en:'Xiong Yan – long reign, extended Chu territory',      start:-886,  end:-848,  color:'#be185d', row:10, personal:'熊延' },
  { name:'熊勇',   en:'Xiong Yong',                                          start:-847,  end:-838,  color:'#f472b6', row:10, personal:'熊勇' },
  { name:'熊嚴',   en:'Xiong Yan II',                                        start:-837,  end:-828,  color:'#f9a8d4', row:10, personal:'熊嚴' },
  { name:'熊霜',   en:'Xiong Shuang',                                        start:-827,  end:-822,  color:'#ec4899', row:10, personal:'熊霜' },
  { name:'熊徇',   en:'Xiong Xun',                                           start:-821,  end:-800,  color:'#be185d', row:10, personal:'熊徇' },
  { name:'熊鄂',   en:'Xiong E',                                             start:-799,  end:-791,  color:'#f472b6', row:10, personal:'熊鄂' },
  { name:'熊儀',   en:'Xiong Yi II (若敖) – 若敖之族 clan rose to power',  start:-790,  end:-764,  color:'#f9a8d4', row:10, personal:'熊儀' },
  { name:'熊坎',   en:'Xiong Kan (宵敖)',                                    start:-763,  end:-758,  color:'#ec4899', row:10, personal:'熊坎' },
  { name:'熊眴',   en:'Xiong Xuan (蚡冒) – fought Sui, expanded north',     start:-757,  end:-741,  color:'#be185d', row:10, personal:'熊眴' },
  { name:'武王',   en:'King Wu of Chu (熊通) – first to self-proclaim「王」(king); 「我蠻夷也，不與中國之號諡」', start:-740, end:-690, color:'#f472b6', row:10, personal:'熊通', wikiEn:'King_Wu_of_Chu' },
  { name:'文王',   en:'King Wen of Chu – moved capital to 郢; conquered Shen, Deng',      start:-689, end:-675, color:'#f9a8d4', row:10, personal:'熊貲' },
  { name:'堵敖',   en:'Duke Du Ao – killed by brother (who became 成王)',    start:-674,  end:-672,  color:'#ec4899', row:10, personal:'熊囏' },
  { name:'成王',   en:'King Cheng of Chu – major expansion; defeated at 城濮 by Jin -632; forced suicide by son', start:-671, end:-626, color:'#be185d', row:10, personal:'熊惲', wikiEn:'King_Cheng_of_Chu' },
  { name:'穆王',   en:'King Mu of Chu (商臣) – forced father 成王 to suicide; continued expansion', start:-625, end:-614, color:'#f472b6', row:10, personal:'熊商臣' },
  { name:'莊王',   en:'King Zhuang of Chu – Spring & Autumn hegemon; 問鼎中原; one of greatest Chu rulers', start:-613, end:-591, color:'#f9a8d4', row:10, personal:'熊旅', wikiEn:'King_Zhuang_of_Chu' },
  { name:'共王',   en:'King Gong of Chu – Battle of Yanling -575 vs Jin; Chu-Jin stalemate', start:-590, end:-560, color:'#ec4899', row:10, personal:'熊審' },
  { name:'康王',   en:'King Kang of Chu',                                    start:-559,  end:-545,  color:'#be185d', row:10, personal:'熊昭' },
  { name:'郟敖',   en:'King Jia Ao – nephew; killed by uncle 熊圍 who seized throne', start:-544, end:-541, color:'#f472b6', row:10, personal:'熊員' },
  { name:'靈王',   en:'King Ling of Chu – megalomaniac; built 章華台; died in rebellion', start:-540, end:-529, color:'#f9a8d4', row:10, personal:'熊圍' },
  { name:'平王',   en:'King Ping of Chu – killed Wuzixu\'s (伍子胥) father & brother; 伍 fled to Wu for revenge', start:-528, end:-516, color:'#ec4899', row:10, personal:'熊棄疾', wikiEn:'King_Ping_of_Chu' },
  { name:'昭王',   en:'King Zhao of Chu – Wu armies sacked 郢 -506; 申包胥 cried for Qin aid; kingdom restored', start:-515, end:-489, color:'#be185d', row:10, personal:'熊珍', wikiEn:'King_Zhao_of_Chu' },
  { name:'惠王',   en:'King Hui of Chu – 56-year reign; executed 白公勝 rebellion; 墨子 era',  start:-488, end:-432, color:'#f472b6', row:10, personal:'熊章' },
  { name:'簡王',   en:'King Jian of Chu',                                    start:-431,  end:-408,  color:'#f9a8d4', row:10, personal:'熊中' },
  { name:'聲王',   en:'King Sheng of Chu – killed by common bandits (盜)',   start:-407,  end:-402,  color:'#ec4899', row:10, personal:'熊當' },
  { name:'悼王',   en:'King Dao of Chu – hired Wu Qi (吳起) for reforms; nobles killed 吳起 at his funeral', start:-401, end:-381, color:'#be185d', row:10, personal:'熊疑' },
  { name:'肅王',   en:'King Su of Chu',                                      start:-380,  end:-370,  color:'#f472b6', row:10, personal:'熊臧' },
  { name:'宣王',   en:'King Xuan of Chu – 申侯之亂; 楚威王\'s father',      start:-369,  end:-340,  color:'#f9a8d4', row:10, personal:'熊良夫' },
  { name:'威王',   en:'King Wei of Chu – defeated 越; Chu at territorial peak; 「縱橫家」era', start:-339, end:-329, color:'#ec4899', row:10, personal:'熊商' },
  { name:'懷王',   en:'King Huai of Chu – 屈原 served him; deceived by Qin\'s 張儀; died in Qin captivity', start:-328, end:-299, color:'#be185d', row:10, personal:'熊槐', wikiEn:'King_Huai_of_Chu' },
  { name:'頃襄王', en:'King Qingxiang – Qin\'s 白起 sacked 郢 -278; 屈原 drowned; capital moved to 陳', start:-298, end:-263, color:'#f472b6', row:10, personal:'熊橫', wikiEn:'King_Qingxiang_of_Chu' },
  { name:'考烈王', en:'King Kaoli – 春申君 era; last powerful Chu king; moved capital to 壽春', start:-262, end:-238, color:'#f9a8d4', row:10, personal:'熊完' },
  { name:'幽王',   en:'King You of Chu',                                     start:-237,  end:-228,  color:'#ec4899', row:10, personal:'熊悍' },
  { name:'哀王',   en:'King Ai of Chu – killed by 負芻 after only weeks on throne', start:-227, end:-226, color:'#be185d', row:10, personal:'熊猶' },
  { name:'負芻',   en:'King Fu Chu (負芻) – last Chu king; Qin\'s 王翦 conquered Chu -223', start:-226, end:-223, color:'#f472b6', row:10, personal:'熊負芻' },
];
