// 周朝諸侯國：韓趙魏燕鄭衛魯吳越蔡陳
// Row 11=韓, 12=趙, 13=魏, 14=燕, 15=鄭, 16=衛, 17=魯, 18=吳, 19=越, 20=蔡, 21=陳
const ZH_STATES2 = [

  // ── ROW 11 韓國 ─────────────────────────────────────────────────────────────
  // 韓氏在晉国为卿，三家分晋后独立建国，前230年被秦所灭
  { name:'韓萬',   en:'Han Wan – Han clan founder in Jin',                    start:-748, end:-709, color:'#f87171', row:11, personal:'韓萬',   wikiEn:'Han_clan' },
  { name:'韓賕伯', en:'Han Qiubo',                                             start:-709, end:-676, color:'#fca5a5', row:11, personal:'韓賕伯' },
  { name:'韓簡',   en:'Han Jian',                                              start:-676, end:-651, color:'#ef4444', row:11, personal:'韓簡' },
  { name:'韓輿',   en:'Han Yu',                                                start:-651, end:-627, color:'#dc2626', row:11, personal:'韓輿' },
  { name:'韓厥',   en:'Han Jue (Xianzi) – saved Zhao Orphan',                 start:-627, end:-587, color:'#f87171', row:11, personal:'韓厥',   wikiEn:'Han_Jue' },
  { name:'韓穿',   en:'Han Chuan',                                             start:-587, end:-566, color:'#fca5a5', row:11, personal:'韓穿' },
  { name:'韓起',   en:'Han Qi (Xuanzi)',                                       start:-566, end:-514, color:'#ef4444', row:11, personal:'韓起' },
  { name:'韓不信', en:'Han Buxin (Jianzi)',                                    start:-514, end:-490, color:'#dc2626', row:11, personal:'韓不信' },
  { name:'韓庚',   en:'Han Geng (Zhuangzi)',                                   start:-490, end:-453, color:'#f87171', row:11, personal:'韓庚' },
  { name:'韓虔',   en:'Han Qian (Kangzi) – Battle of Jinyang -453',           start:-453, end:-424, color:'#fca5a5', row:11, personal:'韓虔',   wikiEn:'Han_Qian' },
  { name:'韓景侯', en:'Han Jinghou – Han recognized as state -403',           start:-424, end:-400, color:'#ef4444', row:11, personal:'韓虔',   wikiEn:'Han_state' },
  { name:'韓烈侯', en:'Han Liehou',                                            start:-400, end:-387, color:'#dc2626', row:11, personal:'韓取' },
  { name:'韓文侯', en:'Han Wenhou',                                            start:-387, end:-377, color:'#f87171', row:11, personal:'韓猷' },
  { name:'韓哀侯', en:'Han Aihou – annexed Zheng -375',                       start:-377, end:-371, color:'#fca5a5', row:11, personal:'韓屯蒙',  wikiEn:'Han_state' },
  { name:'韓懿侯', en:'Han Yihou',                                             start:-371, end:-359, color:'#ef4444', row:11, personal:'韓若山' },
  { name:'韓昭侯', en:'Han Zhaohou – Shen Buhai reforms',                     start:-359, end:-333, color:'#dc2626', row:11, personal:'韓武',    wikiEn:'Marquis_Zhao_of_Han' },
  { name:'韓宣惠王',en:'Han Xuanhuiwang – first use of "king"',               start:-333, end:-312, color:'#f87171', row:11, personal:'韓康' },
  { name:'韓襄王', en:'Han Xiangwang',                                         start:-312, end:-296, color:'#fca5a5', row:11, personal:'韓倉' },
  { name:'韓釐王', en:'Han Liwang',                                            start:-296, end:-272, color:'#ef4444', row:11, personal:'韓咎' },
  { name:'韓桓惠王',en:'Han Huanhuiwang',                                     start:-272, end:-239, color:'#dc2626', row:11, personal:'韓然' },
  { name:'韓王安', en:'Han Wang An – Han conquered by Qin -230',              start:-239, end:-230, color:'#f87171', row:11, personal:'韓安',    wikiEn:'King_An_of_Han' },

  // ── ROW 12 趙國 ─────────────────────────────────────────────────────────────
  // 趙氏在晉为卿，三家分晋后独立，前228年被秦所灭
  { name:'趙衰',   en:'Zhao Cui (Chengzi) – companion of Jin Wengong',        start:-655, end:-622, color:'#a78bfa', row:12, personal:'趙衰',   wikiEn:'Zhao_Cui' },
  { name:'趙盾',   en:'Zhao Dun (Xuanzi) – Zhao Orphan story',               start:-622, end:-601, color:'#c4b5fd', row:12, personal:'趙盾',   wikiEn:'Zhao_Dun' },
  { name:'趙朔',   en:'Zhao Shuo – Zhao Orphan\'s father',                   start:-601, end:-597, color:'#8b5cf6', row:12, personal:'趙朔' },
  { name:'趙武',   en:'Zhao Wu (Wenzi) – the Zhao Orphan',                   start:-583, end:-541, color:'#7c3aed', row:12, personal:'趙武',   wikiEn:'Zhao_Wu' },
  { name:'趙景叔', en:'Zhao Jingshu',                                          start:-541, end:-519, color:'#a78bfa', row:12, personal:'趙成' },
  { name:'趙鞅',   en:'Zhao Yang (Jianzi) – built power base',               start:-519, end:-476, color:'#c4b5fd', row:12, personal:'趙鞅',   wikiEn:'Zhao_Yang' },
  { name:'趙毋恤', en:'Zhao Wuxu (Xiangzi) – Battle of Jinyang -453',        start:-476, end:-425, color:'#8b5cf6', row:12, personal:'趙毋恤', wikiEn:'Zhao_Wuxu' },
  { name:'趙浣',   en:'Zhao Huan (Xianzi)',                                   start:-425, end:-408, color:'#7c3aed', row:12, personal:'趙浣' },
  { name:'趙烈侯', en:'Zhao Liehou – Zhao recognized as state -403',         start:-408, end:-387, color:'#a78bfa', row:12, personal:'趙籍',   wikiEn:'Zhao_state' },
  { name:'趙武侯', en:'Zhao Wuhou',                                            start:-387, end:-375, color:'#c4b5fd', row:12, personal:'趙武侯' },
  { name:'趙敬侯', en:'Zhao Jinghou',                                          start:-375, end:-350, color:'#8b5cf6', row:12, personal:'趙章' },
  { name:'趙成侯', en:'Zhao Chenghou',                                         start:-350, end:-326, color:'#7c3aed', row:12, personal:'趙種' },
  { name:'趙肅侯', en:'Zhao Suhou',                                            start:-326, end:-299, color:'#a78bfa', row:12, personal:'趙語' },
  { name:'趙武靈王',en:'Zhao Wulingwang – Hu Fu Qi She reforms',             start:-299, end:-295, color:'#c4b5fd', row:12, personal:'趙雍',   wikiEn:'King_Wuling_of_Zhao' },
  { name:'趙惠文王',en:'Zhao Huiwenwang – Lian Po & Lin Xiangru era',        start:-295, end:-265, color:'#8b5cf6', row:12, personal:'趙何',   wikiEn:'King_Huiwen_of_Zhao' },
  { name:'趙孝成王',en:'Zhao Xiaochengwang – Battle of Changping -260',      start:-265, end:-245, color:'#7c3aed', row:12, personal:'趙丹',   wikiEn:'King_Xiaocheng_of_Zhao' },
  { name:'趙悼襄王',en:'Zhao Daoxiangwang',                                  start:-245, end:-236, color:'#a78bfa', row:12, personal:'趙偃' },
  { name:'趙幽繆王',en:'Zhao Youmiuwang – Zhao conquered by Qin -228',       start:-236, end:-228, color:'#c4b5fd', row:12, personal:'趙遷',   wikiEn:'King_Youmiu_of_Zhao' },

  // ── ROW 13 魏國 ─────────────────────────────────────────────────────────────
  // 魏氏在晉为卿，三家分晋后独立，前225年被秦所灭
  { name:'魏犨',   en:'Wei Chou (Wuzi) – accompanied Jin Wengong',           start:-655, end:-628, color:'#fbbf24', row:13, personal:'魏犨',   wikiEn:'Wei_Chou' },
  { name:'魏顆',   en:'Wei Ke – Jiecao Baoen story',                          start:-628, end:-607, color:'#fde68a', row:13, personal:'魏顆' },
  { name:'魏錡',   en:'Wei Qi (Lvji)',                                         start:-607, end:-587, color:'#f59e0b', row:13, personal:'魏錡' },
  { name:'魏絳',   en:'Wei Jiang (Zhuangzi) – He Rong policy',               start:-587, end:-558, color:'#d97706', row:13, personal:'魏絳',   wikiEn:'Wei_Jiang' },
  { name:'魏舒',   en:'Wei Shu (Xianzi)',                                      start:-558, end:-509, color:'#fbbf24', row:13, personal:'魏舒' },
  { name:'魏侈',   en:'Wei Chi (Jianzi)',                                      start:-509, end:-480, color:'#fde68a', row:13, personal:'魏侈' },
  { name:'魏駒',   en:'Wei Ju (Huanzi) – Battle of Jinyang -453',            start:-480, end:-445, color:'#f59e0b', row:13, personal:'魏駒' },
  { name:'魏斯',   en:'Wei Si (Wenhou) – hired Li Kui & Wu Qi',              start:-445, end:-396, color:'#d97706', row:13, personal:'魏斯',   wikiEn:'Marquis_Wen_of_Wei' },
  { name:'魏擊',   en:'Wei Ji (Wuhou)',                                        start:-396, end:-370, color:'#fbbf24', row:13, personal:'魏擊',   wikiEn:'Marquis_Wu_of_Wei' },
  { name:'魏罃',   en:'Wei Ying (Huiwang) – Battles of Guiling & Maling',    start:-370, end:-319, color:'#fde68a', row:13, personal:'魏罃',   wikiEn:'King_Hui_of_Wei' },
  { name:'魏嗣',   en:'Wei Si (Xiang Wang) – Mencius at court',              start:-319, end:-296, color:'#f59e0b', row:13, personal:'魏嗣' },
  { name:'魏遫',   en:'Wei Su (Zhaowang)',                                     start:-296, end:-277, color:'#d97706', row:13, personal:'魏遫' },
  { name:'魏圉',   en:'Wei Yu (Anli Wang) – Xinlingjun steals tally',        start:-277, end:-243, color:'#fbbf24', row:13, personal:'魏圉',   wikiEn:'King_Anxi_of_Wei' },
  { name:'魏增',   en:'Wei Zeng (Jingmin Wang)',                              start:-243, end:-228, color:'#fde68a', row:13, personal:'魏增' },
  { name:'魏假',   en:'Wei Jia – Wei conquered by Qin -225',                 start:-228, end:-225, color:'#f59e0b', row:13, personal:'魏假',   wikiEn:'King_Jia_of_Wei' },

  // ── ROW 14 燕國 ─────────────────────────────────────────────────────────────
  // 周初封国，前222年被秦所灭，是最后被灭的诸侯国之一
  { name:'召公奭', en:'Duke Shao of Yan – founder, companion of Zhou Gong',  start:-1046, end:-1000, color:'#67e8f9', row:14, personal:'召公奭', wikiEn:'Duke_Shao_of_Zhou' },
  { name:'燕侯克', en:'Yan Hou Ke',                                            start:-1000, end:-970, color:'#22d3ee', row:14, personal:'燕侯克' },
  { name:'燕侯旨', en:'Yan Hou Zhi',                                           start:-970, end:-940, color:'#0891b2', row:14, personal:'燕侯旨' },
  { name:'燕惠侯', en:'Yan Huihou',                                            start:-940, end:-904, color:'#0e7490', row:14, personal:'燕惠侯' },
  { name:'燕釐侯', en:'Yan Lihou',                                             start:-904, end:-865, color:'#67e8f9', row:14, personal:'燕釐侯' },
  { name:'燕頃侯', en:'Yan Qinghou',                                           start:-865, end:-827, color:'#22d3ee', row:14, personal:'燕頃侯' },
  { name:'燕哀侯', en:'Yan Aihou',                                             start:-827, end:-796, color:'#0891b2', row:14, personal:'燕哀侯' },
  { name:'燕鄭侯', en:'Yan Zhenghou',                                          start:-796, end:-765, color:'#0e7490', row:14, personal:'燕鄭侯' },
  { name:'燕繆侯', en:'Yan Mouhou',                                            start:-765, end:-729, color:'#67e8f9', row:14, personal:'燕繆侯' },
  { name:'燕宣侯', en:'Yan Xuanhou',                                           start:-729, end:-711, color:'#22d3ee', row:14, personal:'燕宣侯' },
  { name:'燕桓侯', en:'Yan Huanhou',                                           start:-711, end:-698, color:'#0891b2', row:14, personal:'燕桓侯' },
  { name:'燕莊公', en:'Yan Zhuanggong',                                        start:-698, end:-691, color:'#0e7490', row:14, personal:'燕莊公' },
  { name:'燕襄公', en:'Yan Xianggong – Qi Huan Gong rescued Yan -664',       start:-691, end:-658, color:'#67e8f9', row:14, personal:'燕襄公' },
  { name:'燕桓公', en:'Yan Huangong',                                          start:-658, end:-618, color:'#22d3ee', row:14, personal:'燕桓公' },
  { name:'燕宣公', en:'Yan Xuangong',                                          start:-618, end:-602, color:'#0891b2', row:14, personal:'燕宣公' },
  { name:'燕昭公', en:'Yan Zhaogong',                                          start:-602, end:-587, color:'#0e7490', row:14, personal:'燕昭公' },
  { name:'燕武公', en:'Yan Wugong',                                            start:-587, end:-574, color:'#67e8f9', row:14, personal:'燕武公' },
  { name:'燕文公', en:'Yan Wengong',                                           start:-574, end:-555, color:'#22d3ee', row:14, personal:'燕文公' },
  { name:'燕懿公', en:'Yan Yigong',                                            start:-555, end:-549, color:'#0891b2', row:14, personal:'燕懿公' },
  { name:'燕惠公', en:'Yan Huigong',                                           start:-549, end:-544, color:'#0e7490', row:14, personal:'燕惠公' },
  { name:'燕悼公', en:'Yan Daogong',                                           start:-544, end:-536, color:'#67e8f9', row:14, personal:'燕悼公' },
  { name:'燕共公', en:'Yan Gonggong',                                          start:-536, end:-530, color:'#22d3ee', row:14, personal:'燕共公' },
  { name:'燕平公', en:'Yan Pinggong',                                          start:-530, end:-523, color:'#0891b2', row:14, personal:'燕平公' },
  { name:'燕簡公', en:'Yan Jiangong',                                          start:-523, end:-505, color:'#0e7490', row:14, personal:'燕簡公' },
  { name:'燕獻公', en:'Yan Xiangong',                                          start:-505, end:-492, color:'#67e8f9', row:14, personal:'燕獻公' },
  { name:'燕孝公', en:'Yan Xiaogong',                                          start:-492, end:-455, color:'#22d3ee', row:14, personal:'燕孝公' },
  { name:'燕成公', en:'Yan Chenggong',                                         start:-455, end:-432, color:'#0891b2', row:14, personal:'燕成公' },
  { name:'燕湣公', en:'Yan Mingong',                                           start:-432, end:-373, color:'#0e7490', row:14, personal:'燕湣公' },
  { name:'燕釐公', en:'Yan Xigong',                                            start:-373, end:-362, color:'#67e8f9', row:14, personal:'燕釐公' },
  { name:'燕桓公', en:'Yan Huangong (2nd)',                                    start:-362, end:-333, color:'#22d3ee', row:14, personal:'燕桓公' },
  { name:'燕文公', en:'Yan Wengong (2nd)',                                     start:-333, end:-321, color:'#0891b2', row:14, personal:'燕文公' },
  { name:'燕易王', en:'Yan Yiwang',                                            start:-321, end:-312, color:'#0e7490', row:14, personal:'燕易王' },
  { name:'燕昭王', en:'Yan Zhaowang – Golden Terrace, hired Yue Yi',         start:-312, end:-279, color:'#67e8f9', row:14, personal:'燕昭王', wikiEn:'King_Zhao_of_Yan' },
  { name:'燕惠王', en:'Yan Huiwang – dismissed Yue Yi, lost Qi gains',       start:-279, end:-272, color:'#22d3ee', row:14, personal:'燕惠王' },
  { name:'燕武成王',en:'Yan Wuchengwang',                                     start:-272, end:-258, color:'#0891b2', row:14, personal:'燕武成王' },
  { name:'燕孝王', en:'Yan Xiaowang',                                          start:-258, end:-255, color:'#0e7490', row:14, personal:'燕孝王' },
  { name:'燕王喜', en:'Yan Wang Xi – Jing Ke assassination attempt; Yan conquered -222', start:-255, end:-222, color:'#67e8f9', row:14, personal:'燕王喜', wikiEn:'King_Xi_of_Yan' },

  // ── ROW 15 鄭國 ─────────────────────────────────────────────────────────────
  // 西周末封国，春秋小霸，前375年被韩所灭
  { name:'鄭桓公', en:'Zheng Huangong – founder, died in 犬戎 attack -771', start:-806, end:-771, color:'#6ee7b7', row:15, personal:'姬友',   wikiEn:'Duke_Huan_of_Zheng' },
  { name:'鄭武公', en:'Zheng Wugong – helped Zhou move east',               start:-770, end:-743, color:'#34d399', row:15, personal:'姬掘突', wikiEn:'Duke_Wu_of_Zheng' },
  { name:'鄭莊公', en:'Zheng Zhuanggong – Spring & Autumn minor hegemon',   start:-743, end:-701, color:'#10b981', row:15, personal:'姬寤生', wikiEn:'Duke_Zhuang_of_Zheng' },
  { name:'鄭昭公', en:'Zheng Zhaogong (1st reign)',                          start:-701, end:-700, color:'#059669', row:15, personal:'姬忽' },
  { name:'鄭厲公', en:'Zheng Ligong (1st reign)',                            start:-700, end:-694, color:'#6ee7b7', row:15, personal:'姬突' },
  { name:'鄭昭公', en:'Zheng Zhaogong (2nd reign)',                          start:-694, end:-695, color:'#34d399', row:15, personal:'姬忽' },
  { name:'鄭子亹', en:'Zheng Zimao – killed at Qi',                          start:-695, end:-694, color:'#10b981', row:15, personal:'姬亹' },
  { name:'鄭子嬰', en:'Zheng Ziying',                                        start:-694, end:-680, color:'#059669', row:15, personal:'姬嬰' },
  { name:'鄭厲公', en:'Zheng Ligong (2nd reign)',                            start:-680, end:-673, color:'#6ee7b7', row:15, personal:'姬突' },
  { name:'鄭文公', en:'Zheng Wengong – long 44-year reign',                 start:-673, end:-628, color:'#34d399', row:15, personal:'姬踕',   wikiEn:'Duke_Wen_of_Zheng' },
  { name:'鄭穆公', en:'Zheng Mugong',                                        start:-628, end:-606, color:'#10b981', row:15, personal:'姬蘭' },
  { name:'鄭靈公', en:'Zheng Linggong – killed over turtle soup',            start:-606, end:-605, color:'#059669', row:15, personal:'姬夷' },
  { name:'鄭襄公', en:'Zheng Xianggong – surrendered to Chu -597',          start:-605, end:-587, color:'#6ee7b7', row:15, personal:'姬堅' },
  { name:'鄭悼公', en:'Zheng Daogong',                                       start:-587, end:-585, color:'#34d399', row:15, personal:'姬費' },
  { name:'鄭成公', en:'Zheng Chenggong',                                     start:-585, end:-571, color:'#10b981', row:15, personal:'姬睔' },
  { name:'鄭釐公', en:'Zheng Xigong',                                        start:-571, end:-566, color:'#059669', row:15, personal:'姬惲' },
  { name:'鄭簡公', en:'Zheng Jiangong – Zichan as minister',                start:-566, end:-530, color:'#6ee7b7', row:15, personal:'姬嘉' },
  { name:'鄭定公', en:'Zheng Dinggong',                                      start:-530, end:-514, color:'#34d399', row:15, personal:'姬寧' },
  { name:'鄭獻公', en:'Zheng Xiangong',                                      start:-514, end:-501, color:'#10b981', row:15, personal:'姬虿' },
  { name:'鄭聲公', en:'Zheng Shenggong',                                     start:-501, end:-463, color:'#059669', row:15, personal:'姬勝' },
  { name:'鄭哀公', en:'Zheng Aigong',                                        start:-463, end:-455, color:'#6ee7b7', row:15, personal:'姬易' },
  { name:'鄭共公', en:'Zheng Gonggong',                                      start:-455, end:-424, color:'#34d399', row:15, personal:'姬丑' },
  { name:'鄭幽公', en:'Zheng Yougong – killed by Han forces',               start:-424, end:-423, color:'#10b981', row:15, personal:'姬已' },
  { name:'鄭繻公', en:'Zheng Xugong',                                        start:-423, end:-395, color:'#059669', row:15, personal:'姬骀' },
  { name:'鄭康公', en:'Zheng Kanggong – last ruler, Zheng destroyed by Han -375', start:-395, end:-375, color:'#6ee7b7', row:15, personal:'姬乙', wikiEn:'Duke_Kang_of_Zheng' },

  // ── ROW 16 衛國 ─────────────────────────────────────────────────────────────
  // 周初封国，春秋重要国家，前209年被秦二世废除，是最后存在的周朝封国
  { name:'衛康叔', en:'Wei Kangshu – founder, Zhou Wuwang\'s brother',      start:-1046, end:-1000, color:'#f0abfc', row:16, personal:'姬封',   wikiEn:'Kangshu_of_Wei' },
  { name:'衛考伯', en:'Wei Kaobo',                                            start:-1000, end:-960, color:'#e879f9', row:16, personal:'姬髦' },
  { name:'衛嗣伯', en:'Wei Sibo',                                             start:-960, end:-925, color:'#d946ef', row:16, personal:'姬嗣伯' },
  { name:'衛疌伯', en:'Wei Jiebo',                                            start:-925, end:-895, color:'#a21caf', row:16, personal:'姬疌伯' },
  { name:'衛靖伯', en:'Wei Jingbo',                                           start:-895, end:-868, color:'#f0abfc', row:16, personal:'姬靖伯' },
  { name:'衛貞伯', en:'Wei Zhenbo',                                           start:-868, end:-843, color:'#e879f9', row:16, personal:'姬貞伯' },
  { name:'衛頃侯', en:'Wei Qinghou',                                          start:-843, end:-813, color:'#d946ef', row:16, personal:'姬頃侯' },
  { name:'衛釐侯', en:'Wei Lihou',                                            start:-813, end:-758, color:'#a21caf', row:16, personal:'姬余' },
  { name:'衛共伯', en:'Wei Gongbo – deposed',                                start:-758, end:-757, color:'#f0abfc', row:16, personal:'姬余' },
  { name:'衛武公', en:'Wei Wugong – virtuous lord, reigned 55 years',       start:-757, end:-700, color:'#e879f9', row:16, personal:'姬和',   wikiEn:'Duke_Wu_of_Wei_(state)' },
  { name:'衛莊公', en:'Wei Zhuanggong',                                      start:-700, end:-686, color:'#d946ef', row:16, personal:'姬楊' },
  { name:'衛惠公', en:'Wei Huigong (1st reign)',                             start:-686, end:-669, color:'#a21caf', row:16, personal:'姬朔' },
  { name:'衛黔牟', en:'Wei Qianmu – interim ruler',                          start:-699, end:-688, color:'#f0abfc', row:16, personal:'姬黔牟' },
  { name:'衛懿公', en:'Wei Yigong – loved cranes; Wei destroyed by Di -660',start:-668, end:-660, color:'#e879f9', row:16, personal:'姬赤',   wikiEn:'Duke_Yi_of_Wei_(state)' },
  { name:'衛戴公', en:'Wei Daigong – brief reign after restoration',        start:-660, end:-659, color:'#d946ef', row:16, personal:'姬申' },
  { name:'衛文公', en:'Wei Wengong – rebuilt Wei from ruins',               start:-659, end:-635, color:'#a21caf', row:16, personal:'姬燬',   wikiEn:'Duke_Wen_of_Wei_(state)' },
  { name:'衛成公', en:'Wei Chenggong',                                       start:-635, end:-600, color:'#f0abfc', row:16, personal:'姬鄭' },
  { name:'衛穆公', en:'Wei Mugong',                                          start:-600, end:-589, color:'#e879f9', row:16, personal:'姬遫' },
  { name:'衛定公', en:'Wei Dinggong',                                        start:-589, end:-577, color:'#d946ef', row:16, personal:'姬臧' },
  { name:'衛獻公', en:'Wei Xiangong',                                        start:-577, end:-559, color:'#a21caf', row:16, personal:'姬衎' },
  { name:'衛殤公', en:'Wei Shanggong',                                       start:-559, end:-547, color:'#f0abfc', row:16, personal:'姬秋' },
  { name:'衛獻公', en:'Wei Xiangong (2nd reign)',                            start:-547, end:-544, color:'#e879f9', row:16, personal:'姬衎' },
  { name:'衛襄公', en:'Wei Xianggong',                                       start:-544, end:-535, color:'#d946ef', row:16, personal:'姬惡' },
  { name:'衛靈公', en:'Wei Linggong – Confucius visited Wei',               start:-535, end:-493, color:'#a21caf', row:16, personal:'姬元',   wikiEn:'Duke_Ling_of_Wei' },
  { name:'衛出公', en:'Wei Chugong (1st reign)',                             start:-493, end:-480, color:'#f0abfc', row:16, personal:'姬輒' },
  { name:'衛莊公', en:'Wei Zhuanggong (2nd)',                               start:-480, end:-478, color:'#e879f9', row:16, personal:'姬蒯聵' },
  { name:'衛出公', en:'Wei Chugong (2nd reign)',                             start:-478, end:-470, color:'#d946ef', row:16, personal:'姬輒' },
  { name:'衛悼公', en:'Wei Daogong',                                         start:-470, end:-440, color:'#a21caf', row:16, personal:'姬黔' },
  { name:'衛敬公', en:'Wei Jinggong',                                        start:-440, end:-432, color:'#f0abfc', row:16, personal:'姬弗' },
  { name:'衛昭公', en:'Wei Zhaogong',                                        start:-432, end:-426, color:'#e879f9', row:16, personal:'姬次' },
  { name:'衛懷公', en:'Wei Huaigong',                                        start:-426, end:-425, color:'#d946ef', row:16, personal:'姬邪' },
  { name:'衛慎公', en:'Wei Shengong',                                        start:-425, end:-358, color:'#a21caf', row:16, personal:'姬頹' },
  { name:'衛聲公', en:'Wei Shenggong',                                       start:-358, end:-343, color:'#f0abfc', row:16, personal:'姬訓' },
  { name:'衛成侯', en:'Wei Chenghou – Shang Yang in Wei before Qin',        start:-343, end:-334, color:'#e879f9', row:16, personal:'姬遫' },
  { name:'衛平侯', en:'Wei Pinghou',                                         start:-334, end:-252, color:'#d946ef', row:16, personal:'姬邦' },
  { name:'衛元君', en:'Wei Yuanjun',                                         start:-252, end:-229, color:'#a21caf', row:16, personal:'姬角' },
  { name:'衛君角', en:'Wei Jun Jiao – last ruler, Wei abolished by Qin II -209', start:-229, end:-209, color:'#f0abfc', row:16, personal:'姬角',   wikiEn:'Wei_state_(Zhou)' },

  // ── ROW 17 魯國 ─────────────────────────────────────────────────────────────
  // 周公旦之子伯禽封鲁，孔子故乡，前249年被楚所灭
  { name:'伯禽',   en:'Bo Qin – son of Duke of Zhou, founder of Lu',        start:-1043, end:-988, color:'#bef264', row:17, personal:'伯禽',   wikiEn:'Bo_Qin' },
  { name:'魯考公', en:'Lu Kaogong',                                          start:-988, end:-981, color:'#a3e635', row:17, personal:'姬酋' },
  { name:'魯煬公', en:'Lu Yanggong',                                         start:-981, end:-965, color:'#84cc16', row:17, personal:'姬熙' },
  { name:'魯幽公', en:'Lu Yougong – killed by brother',                      start:-965, end:-964, color:'#65a30d', row:17, personal:'姬宰' },
  { name:'魯魏公', en:'Lu Weigong',                                          start:-964, end:-924, color:'#bef264', row:17, personal:'姬晞' },
  { name:'魯厲公', en:'Lu Ligong',                                           start:-924, end:-888, color:'#a3e635', row:17, personal:'姬擢' },
  { name:'魯獻公', en:'Lu Xiangong',                                         start:-888, end:-855, color:'#84cc16', row:17, personal:'姬具' },
  { name:'魯真公', en:'Lu Zhengong',                                         start:-855, end:-826, color:'#65a30d', row:17, personal:'姬濞' },
  { name:'魯武公', en:'Lu Wugong',                                           start:-826, end:-816, color:'#bef264', row:17, personal:'姬敖' },
  { name:'魯懿公', en:'Lu Yigong',                                           start:-816, end:-807, color:'#a3e635', row:17, personal:'姬戲' },
  { name:'魯伯御', en:'Lu Boyu – usurper, killed by Zhou king',             start:-807, end:-796, color:'#84cc16', row:17, personal:'姬御' },
  { name:'魯孝公', en:'Lu Xiaogong',                                         start:-796, end:-769, color:'#65a30d', row:17, personal:'姬稱' },
  { name:'魯惠公', en:'Lu Huigong',                                          start:-769, end:-723, color:'#bef264', row:17, personal:'姬弗湟' },
  { name:'魯隱公', en:'Lu Yingong – 1st year of Zuo Zhuan -722',           start:-723, end:-712, color:'#a3e635', row:17, personal:'姬息姑', wikiEn:'Duke_Yin_of_Lu' },
  { name:'魯桓公', en:'Lu Huangong – killed at Qi',                         start:-712, end:-694, color:'#84cc16', row:17, personal:'姬允',   wikiEn:'Duke_Huan_of_Lu' },
  { name:'魯莊公', en:'Lu Zhuanggong – Battle of Changshao -684',          start:-694, end:-662, color:'#65a30d', row:17, personal:'姬同',   wikiEn:'Duke_Zhuang_of_Lu' },
  { name:'魯閔公', en:'Lu Mingong – killed by Qing Fu',                     start:-662, end:-660, color:'#bef264', row:17, personal:'姬啟' },
  { name:'魯僖公', en:'Lu Xigong',                                           start:-660, end:-627, color:'#a3e635', row:17, personal:'姬申',   wikiEn:'Duke_Xi_of_Lu' },
  { name:'魯文公', en:'Lu Wengong',                                          start:-627, end:-609, color:'#84cc16', row:17, personal:'姬興' },
  { name:'魯宣公', en:'Lu Xuangong – 初稅畝 first property tax',            start:-609, end:-591, color:'#65a30d', row:17, personal:'姬倭' },
  { name:'魯成公', en:'Lu Chenggong',                                        start:-591, end:-573, color:'#bef264', row:17, personal:'姬黑肱' },
  { name:'魯襄公', en:'Lu Xianggong',                                        start:-573, end:-542, color:'#a3e635', row:17, personal:'姬午' },
  { name:'魯昭公', en:'Lu Zhaogong – forced into exile by Three Huan',      start:-542, end:-510, color:'#84cc16', row:17, personal:'姬裯',   wikiEn:'Duke_Zhao_of_Lu' },
  { name:'魯定公', en:'Lu Dinggong – Confucius served as minister',        start:-510, end:-495, color:'#65a30d', row:17, personal:'姬宋',   wikiEn:'Duke_Ding_of_Lu' },
  { name:'魯哀公', en:'Lu Aigong – Confucius died -479',                   start:-495, end:-468, color:'#bef264', row:17, personal:'姬將',   wikiEn:'Duke_Ai_of_Lu' },
  { name:'魯悼公', en:'Lu Daogong',                                          start:-468, end:-431, color:'#a3e635', row:17, personal:'姬寧' },
  { name:'魯元公', en:'Lu Yuangong',                                         start:-431, end:-416, color:'#84cc16', row:17, personal:'姬嘉' },
  { name:'魯穆公', en:'Lu Mugong',                                           start:-416, end:-377, color:'#65a30d', row:17, personal:'姬顯' },
  { name:'魯共公', en:'Lu Gonggong',                                         start:-377, end:-353, color:'#bef264', row:17, personal:'姬奮' },
  { name:'魯康公', en:'Lu Kanggong',                                         start:-353, end:-344, color:'#a3e635', row:17, personal:'姬屯' },
  { name:'魯景公', en:'Lu Jinggong',                                         start:-344, end:-316, color:'#84cc16', row:17, personal:'姬匽' },
  { name:'魯平公', en:'Lu Pinggong',                                         start:-316, end:-296, color:'#65a30d', row:17, personal:'姬旅' },
  { name:'魯文公', en:'Lu Wengong (2nd)',                                    start:-296, end:-273, color:'#bef264', row:17, personal:'姬賈' },
  { name:'魯頃公', en:'Lu Qinggong – Lu conquered by Chu -249',            start:-273, end:-249, color:'#a3e635', row:17, personal:'姬讎',   wikiEn:'Duke_Qing_of_Lu' },

  // ── ROW 18 吳國 ─────────────────────────────────────────────────────────────
  // 周太伯后裔，春秋末强国，与越长期争霸，前473年被越所灭
  { name:'太伯',   en:'Tai Bo – elder son of Zhou Tai Wang, founded Wu',    start:-1046, end:-1000, color:'#5eead4', row:18, personal:'太伯',   wikiEn:'Tai_Bo_of_Wu' },
  { name:'仲雍',   en:'Zhong Yong – second son, continued Wu lineage',      start:-1000, end:-970,  color:'#2dd4bf', row:18, personal:'仲雍',   wikiEn:'Zhong_Yong' },
  { name:'季簡',   en:'Ji Jian',                                             start:-970,  end:-940,  color:'#14b8a6', row:18, personal:'季簡' },
  { name:'叔達',   en:'Shu Da',                                              start:-940,  end:-910,  color:'#0d9488', row:18, personal:'叔達' },
  { name:'周章',   en:'Zhou Zhang – recognized by Zhou as Wu lord',         start:-910,  end:-860,  color:'#5eead4', row:18, personal:'周章' },
  { name:'熊遂',   en:'Xiong Sui',                                           start:-860,  end:-825,  color:'#2dd4bf', row:18, personal:'熊遂' },
  { name:'柯相',   en:'Ke Xiang',                                            start:-825,  end:-796,  color:'#14b8a6', row:18, personal:'柯相' },
  { name:'彊鳩夷', en:'Qiang Jiu Yi',                                        start:-796,  end:-770,  color:'#0d9488', row:18, personal:'彊鳩夷' },
  { name:'餘橋疑吾',en:'Yu Qiao Yiwu',                                       start:-770,  end:-748,  color:'#5eead4', row:18, personal:'餘橋疑吾' },
  { name:'柯盧',   en:'Ke Lu',                                               start:-748,  end:-721,  color:'#2dd4bf', row:18, personal:'柯盧' },
  { name:'周繇',   en:'Zhou Yao',                                            start:-721,  end:-700,  color:'#14b8a6', row:18, personal:'周繇' },
  { name:'屈羽',   en:'Qu Yu',                                               start:-700,  end:-680,  color:'#0d9488', row:18, personal:'屈羽' },
  { name:'夷吾',   en:'Yi Wu',                                               start:-680,  end:-660,  color:'#5eead4', row:18, personal:'夷吾' },
  { name:'禽處',   en:'Qin Chu',                                             start:-660,  end:-639,  color:'#2dd4bf', row:18, personal:'禽處' },
  { name:'轉',     en:'Zhuan',                                               start:-639,  end:-619,  color:'#14b8a6', row:18, personal:'轉' },
  { name:'頗高',   en:'Po Gao',                                              start:-619,  end:-584,  color:'#0d9488', row:18, personal:'頗高' },
  { name:'壽夢',   en:'Shou Meng – first to use "King" title; Wu rises',   start:-585,  end:-561,  color:'#5eead4', row:18, personal:'壽夢',   wikiEn:'King_Shoumeng_of_Wu' },
  { name:'諸樊',   en:'Zhu Fan',                                             start:-561,  end:-548,  color:'#2dd4bf', row:18, personal:'諸樊' },
  { name:'餘祭',   en:'Yu Ji',                                               start:-548,  end:-531,  color:'#14b8a6', row:18, personal:'餘祭' },
  { name:'餘昧',   en:'Yu Mei',                                              start:-531,  end:-527,  color:'#0d9488', row:18, personal:'餘昧' },
  { name:'王僚',   en:'Wang Liao – assassinated by Zhuan Zhu',             start:-527,  end:-514,  color:'#5eead4', row:18, personal:'姬僚',   wikiEn:'King_Liao_of_Wu' },
  { name:'吳王闔閭',en:'King Helü – hired Wu Zixu & Sun Zi, sacked Chu',  start:-514,  end:-496,  color:'#2dd4bf', row:18, personal:'姬光',   wikiEn:'King_Helü_of_Wu' },
  { name:'吳王夫差',en:'King Fuchai – defeated Yue, lost to Yue -473',     start:-496,  end:-473,  color:'#14b8a6', row:18, personal:'姬夫差', wikiEn:'King_Fuchai_of_Wu' },

  // ── ROW 19 越國 ─────────────────────────────────────────────────────────────
  // 越王勾践卧薪尝胆复仇灭吴，前306年楚灭越
  { name:'無壬',   en:'Wu Ren – early ancestor of Yue',                     start:-621,  end:-591,  color:'#7dd3fc', row:19, personal:'無壬' },
  { name:'無餘',   en:'Wu Yu',                                               start:-591,  end:-565,  color:'#38bdf8', row:19, personal:'無餘' },
  { name:'夫譚',   en:'Fu Tan',                                              start:-565,  end:-537,  color:'#0ea5e9', row:19, personal:'夫譚' },
  { name:'允常',   en:'Yun Chang – declared King; rival of Wu',            start:-537,  end:-497,  color:'#0284c7', row:19, personal:'允常',   wikiEn:'King_Yunchang_of_Yue' },
  { name:'勾踐',   en:'Gou Jian – sleeping on thorns; destroyed Wu -473', start:-497,  end:-465,  color:'#7dd3fc', row:19, personal:'勾踐',   wikiEn:'King_Goujian_of_Yue' },
  { name:'鹿郢',   en:'Lu Ying',                                             start:-465,  end:-459,  color:'#38bdf8', row:19, personal:'鹿郢' },
  { name:'不壽',   en:'Bu Shou',                                             start:-459,  end:-449,  color:'#0ea5e9', row:19, personal:'不壽' },
  { name:'朱句',   en:'Zhu Gou – conquered Lu -473',                        start:-449,  end:-412,  color:'#0284c7', row:19, personal:'朱句' },
  { name:'越王翳', en:'Yue Wang Yi',                                         start:-412,  end:-375,  color:'#7dd3fc', row:19, personal:'翳' },
  { name:'越王之侯',en:'Yue Wang Zhihou',                                   start:-375,  end:-343,  color:'#38bdf8', row:19, personal:'之侯' },
  { name:'越王無彊',en:'Yue Wang Wuqiang – killed by Chu -306; Yue fragmentd', start:-343, end:-306, color:'#0ea5e9', row:19, personal:'無彊', wikiEn:'King_Wujiang_of_Yue' },

  // ── ROW 20 蔡國 ─────────────────────────────────────────────────────────────
  // 周武王弟蔡叔度之子蔡仲所封，前447年被楚所灭
  { name:'蔡仲',   en:'Cai Zhong – son of Cai Shu, rehabilitated by Zhou Gong', start:-1040, end:-1010, color:'#fef08a', row:20, personal:'胡',    wikiEn:'Cai_Zhong' },
  { name:'蔡伯荒', en:'Cai Bohuang',                                          start:-1010, end:-970,  color:'#fde047', row:20, personal:'蔡伯荒' },
  { name:'蔡宮侯', en:'Cai Gonghou',                                          start:-970,  end:-940,  color:'#eab308', row:20, personal:'蔡宮侯' },
  { name:'蔡厲侯', en:'Cai Lihou',                                            start:-940,  end:-900,  color:'#ca8a04', row:20, personal:'蔡厲侯' },
  { name:'蔡武侯', en:'Cai Wuhou',                                            start:-900,  end:-863,  color:'#fef08a', row:20, personal:'蔡武侯' },
  { name:'蔡夷侯', en:'Cai Yihou',                                            start:-863,  end:-837,  color:'#fde047', row:20, personal:'蔡夷侯' },
  { name:'蔡釐侯', en:'Cai Xihou',                                            start:-837,  end:-810,  color:'#eab308', row:20, personal:'蔡釐侯' },
  { name:'蔡共侯', en:'Cai Gonghou',                                          start:-810,  end:-763,  color:'#ca8a04', row:20, personal:'蔡共侯' },
  { name:'蔡戴侯', en:'Cai Daihou',                                           start:-763,  end:-750,  color:'#fef08a', row:20, personal:'蔡戴侯' },
  { name:'蔡宣侯', en:'Cai Xuanhou',                                          start:-750,  end:-714,  color:'#fde047', row:20, personal:'蔡宣侯' },
  { name:'蔡桓侯', en:'Cai Huanhou',                                          start:-714,  end:-694,  color:'#eab308', row:20, personal:'蔡桓侯' },
  { name:'蔡哀侯', en:'Cai Aihou – seized by Chu; son rescued by Wu',       start:-694,  end:-675,  color:'#ca8a04', row:20, personal:'蔡哀侯' },
  { name:'蔡穆侯', en:'Cai Muhou',                                            start:-675,  end:-646,  color:'#fef08a', row:20, personal:'蔡穆侯' },
  { name:'蔡莊侯', en:'Cai Zhuanghou',                                        start:-646,  end:-612,  color:'#fde047', row:20, personal:'蔡莊侯' },
  { name:'蔡文侯', en:'Cai Wenhou',                                           start:-612,  end:-592,  color:'#eab308', row:20, personal:'蔡文侯' },
  { name:'蔡景侯', en:'Cai Jinghou',                                          start:-592,  end:-543,  color:'#ca8a04', row:20, personal:'蔡景侯' },
  { name:'蔡靈侯', en:'Cai Linghou – killed by Chu Lingwang',               start:-543,  end:-531,  color:'#fef08a', row:20, personal:'蔡靈侯' },
  { name:'蔡平侯', en:'Cai Pinghou – restored after Chu civil war',         start:-531,  end:-522,  color:'#fde047', row:20, personal:'蔡平侯' },
  { name:'蔡悼侯', en:'Cai Daohou',                                           start:-522,  end:-519,  color:'#eab308', row:20, personal:'蔡悼侯' },
  { name:'蔡昭侯', en:'Cai Zhaohou – sought Wu\'s help against Chu',        start:-519,  end:-491,  color:'#ca8a04', row:20, personal:'蔡昭侯', wikiEn:'Marquis_Zhao_of_Cai' },
  { name:'蔡成侯', en:'Cai Chenghou',                                         start:-491,  end:-472,  color:'#fef08a', row:20, personal:'蔡成侯' },
  { name:'蔡聲侯', en:'Cai Shenggong',                                        start:-472,  end:-457,  color:'#fde047', row:20, personal:'蔡聲侯' },
  { name:'蔡元侯', en:'Cai Yuanhou',                                          start:-457,  end:-451,  color:'#eab308', row:20, personal:'蔡元侯' },
  { name:'蔡侯齊', en:'Cai Hou Qi – last ruler, Cai destroyed by Chu -447', start:-451,  end:-447,  color:'#ca8a04', row:20, personal:'蔡侯齊', wikiEn:'Cai_state' },

  // ── ROW 21 陳國 ─────────────────────────────────────────────────────────────
  // 舜之後，封于陈，陈完奔齐（田氏代齐之祖），前478年被楚所灭
  { name:'胡公滿', en:'Hu Gong Man – founder, descendant of Shun',          start:-1046, end:-1012, color:'#fda4af', row:21, personal:'媯滿',   wikiEn:'Duke_Hu_of_Chen' },
  { name:'陳申公', en:'Chen Shengong',                                       start:-1012, end:-986,  color:'#fb7185', row:21, personal:'媯犀侯' },
  { name:'陳相公', en:'Chen Xianggong',                                      start:-986,  end:-966,  color:'#f43f5e', row:21, personal:'媯皋羊' },
  { name:'陳孝公', en:'Chen Xiaogong',                                       start:-966,  end:-932,  color:'#e11d48', row:21, personal:'媯突' },
  { name:'陳慎公', en:'Chen Shengong',                                       start:-932,  end:-895,  color:'#fda4af', row:21, personal:'媯圉戎' },
  { name:'陳幽公', en:'Chen Yougong – killed by Chu',                        start:-895,  end:-877,  color:'#fb7185', row:21, personal:'媯寧' },
  { name:'陳釐公', en:'Chen Ligong',                                         start:-877,  end:-831,  color:'#f43f5e', row:21, personal:'媯孝' },
  { name:'陳武公', en:'Chen Wugong',                                         start:-831,  end:-796,  color:'#e11d48', row:21, personal:'媯靈' },
  { name:'陳夷公', en:'Chen Yigong',                                         start:-796,  end:-781,  color:'#fda4af', row:21, personal:'媯說' },
  { name:'陳平公', en:'Chen Pinggong',                                       start:-781,  end:-778,  color:'#fb7185', row:21, personal:'媯燮' },
  { name:'陳文公', en:'Chen Wengong',                                        start:-778,  end:-745,  color:'#f43f5e', row:21, personal:'媯圉' },
  { name:'陳桓公', en:'Chen Huangong – Chen Wan (陳完) era',                start:-745,  end:-707,  color:'#e11d48', row:21, personal:'媯鮑',   wikiEn:'Duke_Huan_of_Chen' },
  { name:'陳厲公', en:'Chen Ligong – 陳完 fled to Qi this reign',           start:-707,  end:-700,  color:'#fda4af', row:21, personal:'媯躍',   wikiEn:'Duke_Li_of_Chen' },
  { name:'陳莊公', en:'Chen Zhuanggong',                                     start:-700,  end:-693,  color:'#fb7185', row:21, personal:'媯林' },
  { name:'陳宣公', en:'Chen Xuangong',                                       start:-693,  end:-648,  color:'#f43f5e', row:21, personal:'媯杵臼' },
  { name:'陳穆公', en:'Chen Mugong',                                         start:-648,  end:-632,  color:'#e11d48', row:21, personal:'媯款' },
  { name:'陳共公', en:'Chen Gonggong',                                       start:-632,  end:-614,  color:'#fda4af', row:21, personal:'媯朔' },
  { name:'陳靈公', en:'Chen Linggong – licentious; killed by Xia Zhengzhu -599', start:-614, end:-599, color:'#fb7185', row:21, personal:'媯平國', wikiEn:'Duke_Ling_of_Chen' },
  { name:'陳成公', en:'Chen Chenggong',                                      start:-599,  end:-569,  color:'#f43f5e', row:21, personal:'媯午' },
  { name:'陳哀公', en:'Chen Aigong',                                         start:-569,  end:-534,  color:'#e11d48', row:21, personal:'媯弱' },
  { name:'陳惠公', en:'Chen Huigong',                                        start:-534,  end:-506,  color:'#fda4af', row:21, personal:'媯吳' },
  { name:'陳懷公', en:'Chen Huaigong',                                       start:-506,  end:-502,  color:'#fb7185', row:21, personal:'媯柳' },
  { name:'陳湣公', en:'Chen Mingong – last ruler, Chen conquered by Chu -478', start:-502, end:-478, color:'#f43f5e', row:21, personal:'媯越', wikiEn:'Duke_Min_of_Chen' },

];
